modules/ServerAPI/src/server/routes/ServerUtilityFunctions.coffee

Response is now sent as JSON using res.json

Updated how response is sent back to client

---

modules/ServerAPI/src/client/Container.coffee
modules/ServerAPI/src/client/Label.coffee
modules/ServerAPI/src/client/Thing.coffee

Added the "array" stateType value.

Array value type for states

---

modules/ServerAPI/src/server/python/createLiveDesignLiveReportForACAS/create_lr_for_acas.py

Replaced bug-prone while loop with recursive functions for finding the assay and extracting the addable_column_ids.

Fixed infinite loop bug in create_lr_for_acas.py when assay name is widely used and several folders deep

---

modules/CmpdReg/src/client/src/EditParent.js
modules/CmpdReg/src/client/src/MetaLot.js
modules/CmpdReg/src/client/src/Parent.js

Fixed bug to display error and not allow updating parent if stereo category is not selected

Creg bug fix for updating parent with unselected stereo category

---

README.md

Minor correction for viewing logs for all services via docker-compose

Minor README correction for viewing all logs

---

Gruntfile.coffee

Grunt was putting images in "public/image" it should be "public/img"

fixing gruntfile for public img

---

modules/Components/src/client/ACASFormFields.coffee
modules/Components/src/client/PickList.coffee

modified base picklist to add up to 3 first options

enable setting name of first pick list option

---

modules/Components/src/client/ACASFormFields.coffee
modules/Components/src/client/AbstractFormController.coffee

@goshiro2010 , please checkout this branch and test before approving and merging this

Fixes #79 by adding enableInput and disableInput to all the FormFields

---

modules/ServerAPI/src/server/routes/InventoryServiceRoutes.coffee

can handle new query parameters (like, rightLike and maxResults)

Updating getContainerCodeNamesByContainerValue

---

modules/ServerAPI/src/server/routes/InventoryServiceRoutes.coffee

service that takes in a batch code and gives all relevant container info

Service to get container information from batch code.

---

modules/GenericDataParser/src/server/generic_data_parser.R

Merge and then add to RC/1.12.0

Merge feature/struct-services into develop

---

modules/Components/src/client/PickList.coffee

Allowed PickListSelect2Controller to have a placeholder mapped in. Added method to specifically get "code" in case model has different id and code, since "getSelectedCode" actually gets the id attribute for select2. Added alphabetical sorting to ThingLabelComboBoxController.

Appended empty option to all ThingLabelComboBoxController html elements, which fixes #82

---

conf/config.properties.example
modules/SystemTest/spec/serviceTests/SystemTest.coffee
modules/SystemTest/src/server/routes/SystemTestRoutes.coffee

you must add "-nondestructive" to a test you want to run when 
server.systemTest.runDestructive=false

Fixes #137

---

modules/ServerAPI/src/server/routes/InventoryServiceRoutes.coffee

with like, rightLike, maxResults and with parameters.

Issue 154: Implement node route for getContainerStatesByContainerValue

---

modules/ServerAPI/src/server/routes/InventoryServiceRoutes.coffee

New service to get container logs from container codes.

---

modules/ExperimentBrowser/src/client/ExperimentBrowser.coffee
modules/ServerAPI/src/server/routes/ControllerRedirectRoutes.coffee

Fixed bugs in experiment browser and controller redirect routes relating to client.entity.saveInitialsCorpName config

Merge RC/1.12.0 into RC/1.12.1

---

modules/Components/src/client/RealtimeDeviceConnectionView.html

bugfix/styling-RealTimeDeviceConnectionView: fix styling for RealTimeDeviceConnectionView

Merge bugfix/styling-RealTimeDeviceConnectionView into RC/1.12.3

---

modules/ServerAPI/conf/ProtocolConfJSON.coffee
modules/ServerAPI/src/client/Protocol.coffee
modules/ServerAPI/src/client/Protocol.html

feature/sel-required-attributes: Issue #274 (Specify required SEL attributes in Protocol Editor), fix styling for curve display params

Merge feature/sel-required-attributes into develop

---

modules/Components/src/server/routes/AbstractFormControllerRoutes.coffee
modules/ServerAPI/src/client/ExampleThing.coffee
modules/ServerAPI/src/client/ExampleThing.html

fixes #306 add new save locking to example thing

---

app_api_template.coffee
app_template.coffee
modules/ServerAPI/src/server/CustomerSpecificServerFunctions.coffee

on login attempt log ip useragent referrer

---

modules/ServerAPI/src/server/routes/PreferredEntityCodeService.coffee

There is a typo in pickBestLabels that is preventing it from getting the best labels for container tubes

#362: fix pickBestLabels function for ACAS LsContainers

---

modules/CmpdRegAdmin/src/client/AbstractCmpdRegAdmin.coffee
modules/CmpdRegAdmin/src/client/AbstractCmpdRegAdminBrowser.coffee
modules/CmpdRegAdmin/src/client/AbstractCmpdRegAdminBrowserView.html
modules/CmpdRegAdmin/src/client/AbstractCmpdRegAdminView.html
modules/CmpdRegAdmin/src/client/CmpdRegScientist.coffee

feature/add-ignore-option-for-cmpdreg-scientist: added ignore option for all of the cmpdreg admin modules

---

modules/CmpdReg/src/client/src/MetaLot.js

Signed-off-by: Brian Bolt <brian@mcneilco.com>

fixes #458 Cmpd Reg should allow users to edit lots that they Registered

---

modules/ServerAPI/src/server/routes/SyncProjectsUsers.coffee

fixes #562: dont sync to compound project any longer

---

modules/Components/src/client/ACASFormStateDisplayUpdate.coffee
modules/Components/src/client/UtilityFunctions.coffee

Make it so both table and edit value view show human-readable values for codeValues and dateValues

Improved audit table handling for dateValue and codeValue

---

modules/Components/src/client/ACASFormMultiCodeValueCheckbox.coffee
modules/Components/src/client/ACASFormMultiCodeValueCheckbox.html
modules/Components/src/client/ACASFormStateTable.coffee
modules/Components/src/client/AbstractFormController.coffee

Initial MultiCodeValueCheckbox implementation

---

README.md
docker_bob_setup.sh

- Provide updated link to zip containing `jchem.jar`, provided by @brianbolt on #564 
- Provide mock (bob) user creation instructions. 
- Provide instructions for bringing the stack down. 
- Added shell script for creating initial user for local development environment, script provided by @bffrost

Update README, provide mock user creation script

---

modules/CmpdReg/src/client/custom/configuration.json
modules/CmpdReg/src/client/src/MetaLot.js

I made the default true because, while this is a change to the default, I felt it was a reasonable default.

fixes #680 add disableEditMyParents option

---

modules/ServerAPI/src/server/routes/ThingServiceRoutes.coffee

This pull request will have an accompanying acasclient change

fixes #708 put things in bulk and update their file values

---

modules/ServerAPI/src/server/routes/ThingServiceRoutes.coffee

Body was always taking precedence over what was passed as a parameter in the URL so I made it optional to pass in the parameters in the URL and left it so that body continues to override the URL parameters.  Throws a 400 if thingType or thingKind are not passed in either.

757 allow filter by labelType and labelKind for getThingCodeByLabel

---

modules/ServerAPI/src/client/Thing.coffee

Don't error when calling to json on thing which has a missing state

---

modules/Components/src/client/ACASFormFields.coffee
modules/Components/src/client/PickList.coffee

Filter picklists

---

.gitignore
modules/Components/src/client/BasicFileValidateAndSave.coffee
modules/DocForBatches/src/client/DocUpload.coffee

Basic validate and save is broken due to file chooser api change, adding .gitignore items

---

modules/Components/src/client/ACASFormMultiCodeValueCheckbox.coffee

ACASFormMultiCodeValueCheckbox disable input behavior and update collection

---

modules/Components/src/client/ACASFormMultiInteraction.coffee

ACASFormMultiInteractionController should have a function to disable or enable input

---

modules/Components/src/client/ACASFormFields.coffee

ACASFormLSThingInteractionFieldController should be able to be instantiated from an itx picklist stub

---

modules/Components/src/client/ACASFormStateTable.coffee

State table rows with code values which are null should be shown as empty when not required and null values

---

modules/Components/src/client/ACASFormMultiCodeValueCheckbox.coffee
modules/Components/src/client/ACASFormMultiCodeValueCheckbox.html

ACASFormMultiCodeValueCheckboxController should display text when no checkboxes are created

---

modules/Components/src/client/ACASFormFields.coffee

Fix enabling of ACASFormLSHTMLClobValueFieldController and ACASFormLSFileValueFieldController

---

modules/Components/src/client/ACASFormFields.coffee

Save original file name in comments when saving ls through ls file chooser

---

modules/ServerAPI/src/server/routes/FileServices.coffee
package.json

99% of implementation is by  @brianbolt. I applied minor fixes to make sure acasclient automated tests pass, especially including those uploading files.
Fixes #796

Switch upload to use multer

---

modules/Components/src/client/ACASFormFields.coffee
modules/Components/src/client/ACASFormFieldsView.html
modules/Components/src/client/AbstractFormController.coffee
modules/Components/src/client/PickList.coffee
modules/Components/src/client/PickList.html

Ls thing code value picklists should have an option to add a new code value

---

modules/Components/src/client/ACASFormFields.coffee
modules/Components/src/client/ACASFormFieldsView.html
modules/Components/src/client/AbstractFormController.coffee
modules/Components/src/client/PickList.coffee
modules/Components/src/client/PickList.html

Revert "Ls thing code value picklists should have an option to add a new code value"

---

modules/Components/src/client/ACASFormFields.coffee
modules/Components/src/client/ACASFormFieldsView.html
modules/Components/src/client/AbstractFormController.coffee
modules/Components/src/client/PickList.coffee
modules/Components/src/client/PickList.html
modules/ModuleMenus/src/client/ModuleMenusConfiguration.coffee
modules/ServerAPI/src/client/ExampleThing.coffee
modules/ServerAPI/src/client/ExampleThing.css
modules/ServerAPI/src/client/ExampleThing.html

My previous attempt at this had 2 issues that were noted:
1) The picklists didn't insert the "insertSelectedOoption" as the first item in the picklist
2) The ability to filter was not working
I fixed both of these issues

Switching forms to use editable select2 picklists after fixing issue with fitering and showing the insert select text first

---

modules/Components/src/client/ACASFormLocationTree.coffee
modules/Components/src/client/PickList.coffee

ACASFormLocationTree is broken in 1.13.6

---

modules/Logging/src/server/routes/LoggingRoutes.coffee
modules/ServerAPI/src/server/routes/ServerUtilityFunctions.coffee

Secure unauthenticated routes

---

conf/acas-base.env
modules/Standardization/src/client/Standardization.coffee

@bffrost This pull requests contains the re-addition of the .env files which are not used in the normal builds.  This is a temporarily re-introduction until the ticket to remove them is completed.  I plan on using this branch from time to time to push small miscellaneous fixes.

Acas 3 misc

---

modules/Components/src/client/ACASThingBrowser.coffee
modules/Components/src/client/ACASThingBrowserView.html
modules/ModuleMenus/src/client/ModuleMenusConfiguration.coffee
modules/ServerAPI/src/client/ExampleThing.coffee
modules/ServerAPI/src/client/ExampleThing.css

Add ability to filter columns in ls thing browsers

---

modules/CurveAnalysis/src/server/renderCurve.R

Curve Rendering using colorBy can break curve rendering

---

modules/CmpdReg/src/server/routes/CmpdRegRoutes.coffee

Fast structure searching route

---

Dockerfile
docker-compose.yml

Fixes #863
Ran all acasclient tests and all passed:

Update acas-roo-server and acas to use centos stream8

---

.github/workflows/docker-image.yml
Dockerfile

Multiarch builds - acas

---

modules/ServerAPI/src/server/python/createLiveDesignLiveReportForACAS/create_lr_for_acas.py

Copy of approved PR #906 but for 1.13.6 this time

#905 Fix for 1.13.6

---

modules/Components/src/client/ACASThingBrowser.coffee

Escapes html
Fixes #915 
Made sure the html was escaped

Escape html

---

Dockerfile

Added postgresql to ACAS container
Fixes #939
Verified I could run psql and connect to the acas database.

Add psql to ACAS container

---

modules/CmpdReg/src/client/src/AddAlias.js
modules/CmpdReg/src/client/src/Parent.js
modules/CmpdReg/src/server/routes/CmpdRegRoutes.coffee
modules/LotPropertyBulkLoader/src/server/r/LotPropertyBulkLoader.R
modules/SystemTest/src/server/routes/SystemTestRoutes.coffee

Repointed all routes using cmpdreg web controller routes at new acas/api/v1 routes
Fixes #937 
mcneilco/acas-roo-server#309
See testing on mcneilco/acas-roo-server#309

Repointed all routes using cmpdreg web controller routes at new acas/api/v1 routes

---

modules/CmpdRegAdmin/src/server/routes/CmpdRegAdminRoutes.coffee
modules/CmpdRegBulkLoader/src/server/routes/CmpdRegBulkLoaderRoutes.coffee
modules/CodeTablesAdmin/src/client/AbstractCodeTablesAdmin.coffee
modules/CodeTablesAdmin/src/server/routes/CodeTablesAdminRoutes.coffee
modules/Login/src/server/routes/loginRoutes.coffee

- Found that wrong-case Lot Chemist gets picked up by this bit of code in Node before making it to Roo. Added a tweak to make the author check case insensitive.
- I'm concerned this introduces a new bug where incoming username "Bob" won't be cast to existing username "bob". I think I need to fix this before merging, but I'm putting this up for conversation.
Ran acasclient tests

ACAS-98: Make sdf loader case-insensitive

---

modules/CmpdRegBulkLoader/src/server/routes/CmpdRegBulkLoaderRoutes.coffee

Pushing it now. This goes along with the already merged Roo logic https://github.com/mcneilco/acas-roo-server/commit/142ca061b90e029629a6f92935619138790d69ea#diff-99c65dfa1ef02a07f0d2262cdbcddbf7617d5789a8579be07e6ca3f7cc059189

I missed pushing a commit in the recent ACAS-98 work. 

---

modules/ExperimentBrowser/src/client/ExperimentBrowserView.html

Fix alignment of "Copy Link" button w/ URL Box

Quick Fix: Alignment of Copy Link Button w/ URL Box of Generate Link Feature 

---

modules/Login/src/server/routes/loginRoutes.coffee

Revert "Fix issue with detection of failed login for applications that require 302 and location"

---

.github/workflows/tagger.yml

Tested in GitHub Actions: https://github.com/mcneilco/acas/actions/runs/2980857495

Fix quote syntax

---

modules/CmpdReg/src/client/MultipleFilePicker/templates/DropView.inc
modules/CmpdReg/src/client/MultipleFilePicker/templates/file_template.inc
modules/CmpdReg/src/client/MultipleFilePicker/templates/file_template_desc.inc
modules/CmpdReg/src/client/MultipleFilePicker/templates/file_template_renderer.inc
modules/CmpdReg/src/client/MultipleFilePicker/templates/jspVersion/file_template_desc_jsp.inc
modules/CmpdReg/src/client/MultipleFilePicker/templates/jspVersion/file_template_jsp.inc
modules/CmpdReg/src/client/MultipleFilePicker/templates/jspVersion/file_template_renderer_jsp.inc
modules/CmpdReg/src/client/custom/AppControllerView.inc
modules/CmpdReg/src/client/custom/LotView_Custom.inc
modules/CmpdReg/src/client/templates/AddAliasView.inc
modules/CmpdReg/src/client/templates/AppControllerView.inc
modules/CmpdReg/src/client/templates/EditParentSearchResultsView.inc
modules/CmpdReg/src/client/templates/EditParentSearchView.inc
modules/CmpdReg/src/client/templates/EditParentView.inc
modules/CmpdReg/src/client/templates/ErrorNotificationView.inc
modules/CmpdReg/src/client/templates/LotForm/MetaLotView.inc
modules/CmpdReg/src/client/templates/LotForm/NewLotSuccessView.inc
modules/CmpdReg/src/client/templates/LotForm/ParentView.inc
modules/CmpdReg/src/client/templates/LotForm/SaltFormView.inc
modules/CmpdReg/src/client/templates/LotForm/jspVersion/LotView_jsp.inc
modules/CmpdReg/src/client/templates/RegSearchResults/RegSearchResultsView.inc
modules/CmpdReg/src/client/templates/RegistrationSearchView.inc
modules/CmpdReg/src/client/templates/RegistrationView.inc
modules/CmpdReg/src/client/templates/Search/SearchFormView.inc
modules/CmpdReg/src/client/templates/Search/SearchResultView.inc
modules/CmpdReg/src/client/templates/Search/SearchResultsView.inc
modules/CmpdReg/src/client/templates/Search/SearchView.inc
modules/CmpdReg/src/client/templates/StructureImageView.inc
modules/CmpdReg/src/client/templates/jspVersion/AddAliasView_jsp.inc

Quick cleanup to replace spaces with tabs in `.inc` files. Many files had a mixture of tabs and spaces. I don't have a preference, but tabs seemed more prevalent already so I went that direction.
No testing. Whitespace change should be safe.

ACAS-465: spaces to tabs in .inc files

---

modules/ServerAPI/src/server/python/acas_ldclient/acasldclient.py

- For LD integration, adds Project acls to a project to users belonging to a specially formatted LD group name `ACAS_ONLY_ACL_GROUP_<Project Name>`
- This is not behind an ACAS feature flag because it's unlikely we need to turn this feature off due to the obscure nature of the LD group name
ACAS-514
Created a project named `TEST`
Created a group named `ACAS_ONLY_ACL_GROUP_TEST`
Added `bbolt` to `ACAS_ONLY_ACL_GROUP_TEST` and verified the get_user output for bbolt was:
```
{
"id": "351",
"username": "bbolt",
"email": "bbolt",
"firstName": "bbolt",
"lastName": "bbolt",
"roles": [
{
"id": "702",
"roleEntry": {
"id": "702",
"lsType": "Project",
"lsKind": "TEST",
"lsTypeAndKind": "Project_TEST",
"roleDescription": "Permission to Project granted by Live Design group(s): …
```

ACAS-515: Add permissions to projects with special ACAS_ONLY_ACL_GROUP_ProjectX formatted name

---

modules/Components/src/client/style.css

- Tweaked the module width of `.bv_outerContainer` which is found only in BasicFileValidateAndSave
Wide
Medium
Wide
Medium
Narrow
Very Narrow
Narrowest
Local testing with different window widths.

ACAS 524: Fix SEL "Next" button being off the screen to the right

---

modules/CurveAnalysis/src/server/renderCurve.R

This is a PR to merge the same changes in https://github.com/mcneilco/acas/pull/1052 to the 2022.4.x release branch.
ACAS-565 
Not tested on 2022.4.x but same fix should apply

ACAS-565: Repeat PR to back merge plot fix into 2022.4.x

---

modules/CmpdReg/src/client/src/PickList.js
modules/Components/src/client/PickList.coffee

Lot Chemist, Protocol Scientist, Experiment Scientist drop down menu don't show names in alphabetical order. We have here two pick list components.
`Stereo Category`, `Chemist`, `Physical State`, `Purity measured by`, `Vendor`, `Retain` units, `Project`, `Amount` units, `Purity` & `Solution Amount` units  uses [PickListSelectController](https://github.com/mcneilco/acas/blob/a2f657ae8d9d6fccceef561fcbb019fb98d72965/modules/CmpdReg/src/client/src/PickList.js#L48)
`Salt`, `Isotope` uses [IsoSaltEquivListController](https://github.com/mcneilco/acas/blob/a2f657ae8d9d6fccceef561fcbb019fb98d72965/modules/CmpdReg/src/client/src/IsoSaltEquiv.js#L178) which has it's own comparator for the collection.
`Status`, `Scientist`, `Project`, `Assay Stage`, `Attach Files > File Type`
`Status`, `Scientist`, …

ACAS-589: Sort PickListList collection items.

---

.github/workflows/upmerge.yml

⬆️ Upmerge release/2023.1.x to release/2023.2.x

---

.github/workflows/docker-image.yml
modules/GenericDataParser/src/server/generic_data_parser.R

1096 read optional experiment status from sel file header block

---

modules/GenericDataParser/src/server/generic_data_parser.R
modules/ServerAPI/src/server/routes/CreateLiveDesignLiveReportForACAS.coffee

*tagged here because the api user for github actions owns the PR and cannot be a reviewer*
@bffrost

⬆️ Upmerge release/2023.2.x to release/2023.3.x

---

docker-compose.yml
modules/Components/src/client/ACASFormChemicalStructure.coffee

⬆️ Upmerge release/2023.3.x to release/2023.4.x

---

modules/GenericDataParser/src/server/generic_data_parser.R

Duplicate of https://github.com/mcneilco/acas/pull/1136 but set to 2023.2.x

Clone of ACAS-729 (Experiment Upload Bug Fix) for 2023.2.x

---

modules/Components/src/client/BasicFileValidateAndSave.coffee
modules/GenericDataParser/src/server/generic_data_parser.R

⬆️ Upmerge release/2024.1.x to release/2024.2.x

---

Dockerfile

- Switches all references from mirror to vault
- I plan on up merging his PR and creating a seperate 
ACAS-744
TBD

ACAS-744: Switch to vault.centos.org as a workaround for stream8 EOL

---

.github/workflows/docker-image.yml
README.md
docker_bob_setup.sh

*tagged here because the api user for github actions owns the PR and cannot be a reviewer*
@bffrost

⬆️ Upmerge release/2024.2.x to release/2024.3.x

---

.github/workflows/docker-image.yml
.github/workflows/tagger.yml
.github/workflows/trigger-tag.yml
.github/workflows/upmerge.yml
Dockerfile
README.md
app_template.coffee
bin/setenv.sh
conf/config.properties.example
docker_bob_setup.sh
modules/CmpdReg/src/client/css/NewCmpdReg_nocompile.css
modules/CodeTablesAdmin/src/server/routes/CodeTablesAdminRoutes.coffee
modules/Components/src/client/ACASFormChemicalStructureView.html
modules/Components/src/client/PickList.coffee
modules/GenericDataParser/src/server/generic_data_parser.R
modules/ServerAPI/src/client/Protocol.coffee
modules/ServerAPI/src/server/Bootstrap.coffee
modules/ServerAPI/src/server/python/createLiveDesignLiveReportForACAS/create_lr_for_acas.py
modules/ServerAPI/src/server/routes/AuthorRoutes.coffee
package.json
requirements.txt

Upmerge release/2025.1.x to master

---

app_template.coffee
conf/config.properties.example
package.json

Revert "ACAS-828 Use postgres for session management"

---

modules/CurveAnalysis/src/server/renderCurve.R

*tagged here because the api user for github actions owns the PR and cannot be a reviewer*
@bffrost

⬆️ Upmerge release/2025.2.x to master
