gulpfile.coffee
currently gulp watch will die if any of the execute scripts throw an error, this fix pipes the error to console.error and continues the process
=> fix gulp execute tasks to not kill watch if they error

modules/Project/src/client/Project.coffee
Validation of saved project codenames with special characters prevented updates to project.
=> Do not validate codename for saved projects

modules/GenericDataParser/src/server/generic_data_parser.R
This fix is for SEL to check the length of the column header to make sure it will fit in the analysis_group_value.ls_kind column
=> Add value kind length check as value kinds are limited to 64 characters

modules/Components/src/client/ACASFormStateTable.coffee, modules/ServerAPI/src/client/ExampleThing.coffee, modules/ServerAPI/src/client/ExampleThing.html
Added uniqueness validation to ACASFormStateTable for columns with fieldSettings.unique: true following example from https://github.com/handsontable/handsontable/issues/3102 . Also passed through fieldSettings.format to control numeric formatting.
=> Added uniqueness validation to ACASFormStateTable

modules/Components/src/client/ACASFormFieldsView.html
icon-th is now wrapped in a box as intended. Fixes #155 
Attached screenshot shows "before" fix
=> Added input-append div to allow for proper display of datepicker. 

modules/ServerAPI/src/server/routes/InventoryServiceRoutes.coffee
getParentVialByDaughterVialBarcode which takes daughterVialBarcode as a query param, and returns a flat object of the barcode/label and codenames for the parent vial, parent well, daughter vial, and daughter well.
advancedSearchContainers: POST route that exposes the deep value/label/interaction searching route in Node.
=> Added two new inventory services:

modules/GenericDataParser/src/server/generic_data_parser.R
Currently protocols created through SEL do not have a scientist value. It should be set to be the same as the scientist for the experiment created through SEL
=> #423: Protocols created via SEL should have scientist set

modules/GenericDataParser/src/server/generic_data_parser.R
Users want to add a flag to an entire dose (all the points at a given concentration) but doing this caused an error because SEL created a tsv upload file that had no treatment group for the dose they knocked out.  The fix is to upload a treatment group with a codeValue of kind "flag status" and value "knocked out".
=> fixes #495: Error when flagging all data points of a dose

modules/GenericDataParser/src/server/generic_data_parser.R
Get protocol by code name returns the protocol without the experiments.  The places where getProtocolById is used do not require the experiments to be returned.
=> fixes #532: Protocols with many experiments cause out of memory error

modules/GenericDataParser/src/server/generic_data_parser.R
The referenced issue (#556 contains the test file.
Here is the new warning generated by this code
=> fixes #556: Replace new line characters in entity reference codes and warn the user of the changed data

package.json
Reverts mcneilco/acas#599
This merge requests breaks ACAS, I'll revisit it later but reverting for now.
=> Revert "Bump csv-parse from 1.3.3 to 4.6.5"

modules/Components/src/client/ACASFormStateTable.coffee
This fixes the duplicate rendering after an update of a thing
=> #619 if re-rendering after a save, we need to destroy the existing state form controller and re-create it

modules/Components/src/client/ACASFormStateTable.coffee
Added a proper listener to `createNewValue` in the right state when StateTableForm values get updated.
In the normal case in Thing.coffee, the `Thing` adds listeners to `createNewValue` for each value in the defaultValues list. The `setValueType` method on the `Value` class from Label.coffee handles detecting changes and ignoring the old value, but then triggers `createNewValue` for another controller to listen for.
Since the values in our StateTableForm are initialized via a slightly different method, they need a separate listener to listen for 'createNewValue'.
Tested that this works for editing saved values, changing filled-in values back to null, and can properly handle multiple changes to the field before a save.
=> Fix updates of saved values in StateTableForm

modules/Components/src/client/ACASFormStateTable.coffee
This fix appears to solve both of these issues:
- StateTable should be read-only and styled in grey/read-only mode
- "autocomplete" and date dropdowns should not be editable
I haven't been able to reproduce the update button being available.
=> #634 set cells to readonly when disabling all inputs

modules/Components/src/client/ACASFormMultiCodeValueCheckbox.coffee
- fix new checkbox value creation to find the correct value
- Also tolerate multiple checkbox toggle events and only create one value per checkbox per save
=> Multi Checkbox save multiple checks

modules/CmpdReg/src/client/custom/configuration.json
there is an accompanying acas-roo-server commit which often provides most of the implementation
=> fixes #673 setting for allowing no structures compounds to be registered as unique parents

modules/CmpdReg/src/client/css/NewCmpdReg_nocompile.css
This fixes a long issue seen on Safari which made its way to Chrome as chrome changed the way it handles something with our css/html
=> fixes #725 cmpd reg button cutoff

modules/Components/src/client/ACASThingBrowser.coffee, modules/Components/src/client/ACASThingBrowserView.html
This fixes a few issues with ACASThingBrowser:
- TinyMCE wasn't rendering when ThingController was instatiated so Clob values were not shown
- Adds the ability to search by recorded date with searches like
- "2021" all recorded date within year 2021
- "2021-04 all recorded date within April 2021
- "2021-04-02 all recorded date on April 2nd 2021
- Adds the ability to search by recordedBy
- Refactors ACASThingBrowser to not require a separate query config
- To update to this branch, classes that extend this class need to
- Rename "toDisplay" option to "configs"
- Remove "query" option
- To display a thing attribute without making it searchable you can add `false` to the `isSearchable` key of the config you are adding (default is to always search by all display values.
=> 752 acas thing browser class

modules/Components/src/client/ACASFormStateTable.coffee
=> New rows in a state table are not rendering automatically so defaults are not rendered properly and can show as an error when they are not.

modules/Components/src/client/ACASFormStateTable.coffee
=> ACASFormStateTableController should be able to start with 0 empty rows if configured

modules/Components/src/client/ACASFormFields.coffee, modules/Components/src/client/ACASFormFieldsView.html, modules/Components/src/client/ACASFormStateTable.coffee, modules/Components/src/client/AbstractFormController.coffee
HTMLClobValue was causing problems because it includes HTML in the saved value, and we were trying to use it to store command-line arguments which should be plaintext.
Implemented an "ACASFormLsClobValueController" tied to type `clobValue` (as opposed to `htmlClobValue`) which creates a simple `textarea` which is resizable.
=> ACAS-133: Add simple textarea clobValue FormField

modules/CmpdRegAdmin/src/client/AbstractCmpdRegAdmin.coffee, modules/CmpdRegAdmin/src/client/AbstractCmpdRegAdminBrowser.coffee, modules/CmpdRegBulkLoader/src/client/CmpdRegBulkLoader.coffee, modules/CodeTablesAdmin/src/client/AbstractCodeTablesAdmin.coffee, modules/CodeTablesAdmin/src/client/AbstractCodeTablesAdminBrowser.coffee, modules/Components/src/client/ACASFormFields.coffee, modules/Components/src/client/ACASFormStateDisplayUpdate.coffee, modules/Components/src/client/ACASThingBrowser.coffee, modules/Components/src/client/RealtimeDeviceConnectionController.coffee, modules/CurveAnalysis/src/client/CurveCurator.coffee, modules/CurveAnalysis/src/client/DoseResponseKiAnalysis.coffee, modules/DocForBatches/src/client/BatchListValidator.coffee, modules/DocForBatches/src/client/DocUpload.coffee, modules/ExperimentBrowser/src/client/ExperimentBrowser.coffee, modules/ModuleMenus/src/client/ModuleMenus.coffee, modules/Project/src/client/Project.coffee, modules/Project/src/client/ProjectBrowser.coffee, modules/ProtocolBrowser/src/client/ProtocolBrowser.coffee, modules/ServerAPI/src/client/AttachFile.coffee, modules/ServerAPI/src/client/AuthorBrowser.coffee, modules/ServerAPI/src/client/BaseEntity.coffee, modules/ServerAPI/src/client/ExampleThing.coffee, modules/ServerAPI/src/client/Experiment.coffee, modules/ServerAPI/src/client/Protocol.coffee
I found that backbone uses underscore's escape method under the hood:
https://github.com/jashkenas/backbone/blob/153dc41616a1f2663e4a86b705fefd412ecb4a7a/backbone.js#L456
So instead of rolling my own escape, I just used _.escape when we are setting .html without a backbone model
=> fixes #826 Use model.escape and _.escape to protect against XSS

modules/Components/src/client/ACASThingBrowser.coffee
Found the issue. I was mistakingly escape the entire value instead of just the things.
=> Fixing acas thing browser rendering

app_template.coffee
Fixes a few places we do this but discovered that Structure Images rendered in base64 in creg were broken without this.
=> Fix issue required to shows base64 images inline

modules/GenericDataParser/src/server/generic_data_parser.R
=> ACAS doesn't catch when a lot is not associated with a project

modules/Components/src/client/ACASThingBrowser.coffee
Fixes #892
Scope jquery changes to only current element
Found a few places in ACASThingBrowserController where changes to HTML were not scoped to current element, so they were unintentionally affecting all ThingBrowser instances.
Used search pattern `[\s+]\$\(["'].bv` to locate these, and didn't find any more within Thing components. There are some hits for this pattern across many files that I did not choose to fix.
#892
I had this situation set up in my local environment, and when I patched this change into the javascript, it fixes the issue. Browsers still each work normally but now the browser + embedded browser situation also works.
=> Scope ACASThingBrowserController HTML changes to only current element

modules/CmpdRegAdmin/src/client/CmpdRegStereoCategory.coffee, modules/CmpdRegAdmin/src/client/CmpdRegVendor.coffee, modules/CodeTablesAdmin/src/client/CodeTablesAssayScientist.coffee, modules/CodeTablesAdmin/src/client/CodeTablesCompoundScientist.coffee
Fixes #898
Fixed validation to check if valid characters is null (0 valid characters)
Fixes #898
Went to each module and verified each disabled the save button when only invalid characters were supplied
Went to each module and saved a code value and verified they showed up in the browser (saved properly).
=> Additional Assay Scientist and Compound scientists fail on all invalid characters

.github/workflows/docker-image.yml, .gitignore, docker-compose.yml, docker_bob_setup.sh
Main features
- Startup basic acas oss instance, download the acasclient and run tests
- If the build does not have equivalent branches in roo/rservices, it falls back to release/1.13.7 (using default git branch as a guide)
- Build all branches but only push release and tags (previously built only tags)
- Make roo wait for database to fully start
- I was seeing some slow database startup times and it was causing an issue where roo wasn't coming up
See action build logs for this here: https://github.com/mcneilco/acas/actions/runs/1989388121
Fixes #896
Built on a "release/" branch to make sure build test and push works
Built on a regular "brianbolt/" branch to make sure build and test works but does not push a docker image
=> Run acasclient tests on build

modules/CodeTablesAdmin/src/client/AbstractCodeTablesAdmin.coffee, modules/CodeTablesAdmin/src/client/AbstractCodeTablesAdminView.html, modules/CodeTablesAdmin/src/client/CodeTablesAssayScientist.coffee, modules/CodeTablesAdmin/src/client/CodeTablesCompoundScientist.coffee, modules/Components/src/client/LSErrorNotification.coffee
Added LsNotificiation widget to the module
Made change to LsNotification widget to show message when they are added (default is true but option to turn off)
Changed attribute name/html to match expected naming in [AbstractFormController](https://github.com/mcneilco/acas/blob/e792b459182406534bf5cffafbb0571ddfc8978f/modules/Components/src/client/AbstractFormController.coffee#L49) 
Changed the event name to `input` which is a more modern browser way of detect field changes (detects any change including pasting)
Fixes #900
Added various errors, cleared them, made sure notifications showed up properly. Made sure I could still register codes
.
=> Validation error messages don't show up in CodeTableAdmin modules

conf/docker/acas/environment/acas.env, conf/docker/db/environment/db.env, conf/docker/postgres/environment/postgres.env, docker-compose.yml
Requires updated mcneilco/acas-postgres:1.13.7 (https://github.com/mcneilco/acas-postgres/pull/4)
Fixes #908 
I build the docker image and added it to my docker-compose.yml in base acas
I deleted on config/docker/**.env files
I ran on acasclient tests and they passed
=> Remove need for extra docker environment files in acas #908

conf/config.properties.example, modules/ServerAPI/src/server/routes/FileServices.coffee
- Set disallowed file types by file extension
- Mimetype filtering doesn't work well because some files share mime types.  Additionally, mimetypes like `application/octet-stream` is for arbitrary binary data and can be many different types.  Because of this, filtering by file extensions only is the best way to go. 
- Use helmet to set strict Content Security Policy on dataFiles routes
- Using the strict CSP and sanbox headers, even if an SVG with a script tag
#918 
- Uploaded disallowed file extensions to data files and made sure they were disallowed
- Removed the disallowed file extension from the config and made sure they were allowed
- Uploaded an SVG with a script tag and verified it was not executed.
=> Disallowed file extensions and datafiles CSP Brianbolt/issue918

conf/docker/acas/environment/acas.env, conf/docker/db/environment/db.env, conf/docker/postgres/environment/postgres.env, docker-compose.yml
Reverts mcneilco/acas#909
This broke certain deployment scenarios which expect .env files to exist
=> Revert "Remove need for extra docker environment files in acas #908"

conf/acas-base.env, conf/config.properties.example, modules/CmpdReg/src/client/custom/LotView_Custom.inc, modules/CmpdReg/src/client/custom/Lot_Custom.js, modules/CmpdReg/src/client/templates/LotForm/ParentView.inc, modules/CmpdReg/src/client/templates/RegSearchResults/RegSearchResultsView.inc
- First commit was to run an auto format on LotCustom.js, the file was badly formatted (mixed indentation).
- Fixed issue with template escape on safe variable evaluation
- Fixed unrelated annoying issue where you click on a radio label and it doesn't select the radio button
- 
Fixes #926 
**Default behavior:**
- Verified default behavior unchanged (no editing lot numbers, auto lot number not filled, auto assigned by backend service).
**autoPopulateNextLotNumber = true**
- Verified UI fills the next lot number (highest saved lot + 1)
- Verified new compounds still get lot 1 as default
**autoPopulateNextLotNumber = true, maxAutoLotNumber=999**
- Verified same behavior as **autoPopulateNextLotNumber = true**
- Verified that if I add a lot 1000 the next auto lot is not 1001 but rather the …
=> Add max auto lot number, fix radio button selection on label

.github/workflows/docker-image.yml
Added `-v` argument to python unittest command
Fixes #935
Ran GitHub Actions and verified updated output during tests
Before:
After:
=> output verbose output when running acasclient tests during GitHub Actions builds

conf/config.properties.example, modules/GenericDataParser/src/server/generic_data_parser.R
Adds a config `server.service.external.preferred.batchid.allowParentAliasLotNames`=true/false for allowing `Parent Alias Lot Names` to be used when requesting `Corporate Batch ID` preferred names in addition to actual  `Lot Corp Name`
`Lot Corp Name` format is defined by:
- `client.cmpdreg.serverSettings.appendSaltCodeToLotName`= true/`false default` 
- `client.cmpdreg.serverSettings.corpBatchFormat`= `corp_batch_saltcode` or `corp_saltcode_batch`
By default they are of the form:
- CMPD-0000001-001
If `client.cmpdreg.serverSettings.appendSaltCodeToLotName` is set to true (which is rare), they could look like:
- if `client.cmpdreg.serverSettings.corpBatchFormat`=`corp_batch_saltcode`
- CMPD-0000001-001-HCl
- or `client.cmpdreg.serverSettings.corpBatchFormat`=`corp_saltcode_batch`
- …
=> Allow SEL upload w/ parent alias values within lot corp name

modules/GenericDataParser/src/server/generic_data_parser.R
#494 is a known issue that yields no warning, but causes the upload to hard fail within Roo. Fixed this by adding an explicit check in SEL validation that will prevent users from proceeding with files like this.
#494 
Added acasclient unit test for this issue, confirmed they were failing before this fix, and confirmed tests pass after adding this fix.
See https://github.com/mcneilco/acasclient/pull/54
=> ACAS-35: Fix SEL issue caused by file containing duplicate result type with different data types

modules/ServerAPI/src/client/Protocol.coffee, modules/ServerAPI/src/client/Protocol.html
Default option of the `Project` field on the Protocol Editor page is `Select Project` which when chosen means the protocol is available to all projects and not bound to one project and so the text is not truly reflecting the behaviour.
We change the text from `Select Project` to `Not Restricted` and add an info icon with a tooltip to explain the behaviour.
=> ACAS-84: Update the "Project" field in "Protocol Editor".

modules/ExperimentBrowser/src/client/ExperimentBrowser.coffee, modules/ExperimentBrowser/src/client/ExperimentBrowserView.html, modules/ServerAPI/src/server/routes/GetLinkExptQueryTool.coffee
Implemented "Generate Link" button and "Copy Link" to clipboard button for experiments alongside the "Open In" button.
Added a new option that can generate a LR link and shows it to the user in a way that is easy to copy. Also added a "Copy Link" button to enable one-click copying. 
The goal of this is to click "generate link" and then wait for the Live Report link to be generated on the ACAS page instead of having the "Open In LiveDesign" selection take the user to a separate page that takes a long time to load. 
Information for this can be found under SDGR [ACAS-272](https://jira.schrodinger.com/browse/ACAS-272)
This work also overlaps with [ACAS-277](https://jira.schrodinger.com/browse/ACAS-277). 
This has been tested using a stubbed LD route and LR link
=> Enhance Open in LD UX Experience 

conf/config.properties.example, modules/CmpdReg/src/client/src/MetaLot.js, modules/CmpdReg/src/server/routes/CmpdRegRoutes.coffee, modules/Login/src/server/routes/loginRoutes.coffee, modules/ServerAPI/src/server/routes/AuthorRoutes.coffee, modules/ServerAPI/src/server/routes/ExperimentServiceRoutes.coffee, modules/ServerAPI/src/server/routes/ServerUtilityFunctions.coffee, modules/ServerAPI/src/server/routes/SetupRoutes.coffee, modules/SystemTest/src/server/routes/SystemTestRoutes.coffee, package.json
- Changed to project roles enable = true and restrict project details by project default to true
- Added acls checks to POST meta lot route
- Added additional acls checks to get met alot route
- Removed checks on client side to just use server side acls
- Introduced node-fetch package
- Fixed some a few minor issues with check has roles and view deleted experiments
ACAS-314
Ran acas client tests
Ran through single reg multiple scenarios with project acls, cmpd reg user vs cmpd reg admin...etc.
=> get meta lot and  post meta lot acls server side checks

modules/ExperimentBrowser/src/client/ExperimentBrowser.coffee, modules/ServerAPI/src/server/routes/GetLinkExptQueryTool.coffee
When deployed in production, ACAS is behind an nginx proxy that only routes certain urls to ACAS. ACAS-277 added a new `/getLinkExptQueryTool` URL but we did not add it to the configuration service that controls that nginx proxy. A simpler solution is to move this route behind a pre-existing url beginning, namely `/api`.
After fixing initial issue, noticed and fixed 2 more issues with the copy link button.
Patched these into javascript on live server, tested features in UI
=> ACAS-328 shift endpoint behind /api so it does not require new proxy settings

modules/Standardization/src/client/Standardization.coffee
If Creg detects that standardization settings have changed but the changed settings do not produced compound changes ACAS should still allow standardization execution otherwise users are blocked from registering compounds and the system is stuck in a state where it "needs standardization".
ACAS-338
Patched fix in server which was exhibiting the behavior above. Enabling standardization allowed for the button to be active regardless of number of changes when the dry run was complete.  Executing stanadarization had the desired effect where no structures were changed but the "needs standardization" flag was set to false when complete.
=> Don't disable standardization if dry run changes is < 1

modules/CmpdRegBulkLoader/src/client/CmpdRegBulkLoader.coffee, modules/CmpdRegBulkLoader/src/client/CmpdRegBulkLoader.html
Previously on the CmpdReg Bulk Loader Admin "Purge Files" menu AFTER you purge a file, you could only download the original SDF. There was no way to access this download through the UI before purging.
- Changed the "File" column to an active hyperlink that downloads the original file 
- Added a new "Report" column to the table of files that has links to download the summary zip associated with each file 
- Tested locally with example .sdf files
=> Added file links to Purge Files page before purging files

modules/Login/src/server/routes/loginRoutes.coffee, modules/ServerAPI/src/client/externalRedirect.jade, modules/ServerAPI/src/client/login.jade
**Steps to Reproduce**
On an ACAS server configured with SAML, when not logged in, try to navigate directly to the acas homepage, i.e. https://example.com/acas
**Expected Results**
Get redirected to Okta for login, then get redirected back to original ACAS url https://example.com/acas
**Actual Results**
Okta sign-in works, but user is sent to https://example.com/ which then redirects to LD homepage
If you then go to https://example.com/acas it works since you are logged in
**Extra Information**
Clicking the relevant ACAS app icon in Okta results in a smooth sign-in that takes you to the ACAS homepage.
- Direct login changes
- Fixed the general issue above by not storing the redirect url in the session
- Added redirect_login parameter to login post from login jade file
- use general …
=> ACAS-346 SSO and direct login redirect clean up (external link UI, host checking and better redirect consistenty)

modules/Components/src/client/BasicFileValidateAndSave.coffee, modules/Components/src/client/OpenExperimentInQueryTool.coffee, modules/Components/src/client/OpenExperimentInQueryToolView.html, modules/ExperimentBrowser/src/client/ExperimentBrowser.coffee, modules/ExperimentBrowser/src/client/ExperimentBrowserView.html
**Steps to Reproduce**
Load an Experiment through the Experiment Loader, and look at the summary from a successful upload.
**Expected Results**
There is a button to Generate Link which will yield a copyable LiveReport link.
The Open in LiveDesign button UX is improved (See [ACAS-277](https://jira.schrodinger.com/browse/ACAS-277))
**Extra Information**
This was an oversight in the spec for [ACAS-272](https://jira.schrodinger.com/browse/ACAS-272) and [ACAS-277](https://jira.schrodinger.com/browse/ACAS-277). Those improvements are live on Experiment Browser but are not present in the SEL summary which is generated in R.
Brian Bolt and Brian Frost discussed a potential technical route to take here, since this fix is non-obvious.
In Brian Bolt's recent Dose Response work, he established a …
=> ACAS-330: Improved "Open In" button UX for SEL summary

modules/CmpdRegBulkLoader/src/client/CmpdRegBulkLoader.coffee
**Please review ACAS-301 before this PR**
There was an issue in the CReg bulk loader where summary files for some .sdfs (with special characters) could not be downloaded before and after registration. Added URI encoding in file download links to fix. 
Tested using an .sdf file with special characters (model 310522#1 (1).sdf), was able to download summary files before and after registration. Also was able to download original .sdf, current .sdf, and summary files from the Purge Files page in the CReg bulk loader.
=> Fixed error downloading summary files for some .sdfs 

modules/CmpdReg/src/server/routes/CmpdRegRoutes.coffee
Add route to swap two parent structures. 
Route to interact with the roo layer.
[ACAS-286](https://jira.schrodinger.com/browse/ACAS-286).
[acas-roo-server](https://github.com/mcneilco/acas-roo-server/pull/342) PR.
I used curl requests to check the API,
```
curl -X POST http://localhost:3000/cmpdreg/swapParentStructures -H 'Content-Type: application/json' --data-raw '{"corpName1": "CMPD-0000001", "corpName2": "CMPD-0000002"}'
```
~In cases duplicate parents exist for a compound, it's still going ahead with the swapping even though duplicates should have been marked. See [acas-roo-server](https://github.com/mcneilco/acas-roo-server/pull/342) PR.~
=> Add route to swap two parent structures.

modules/CmpdReg/src/client/CmpdReg.jade, modules/CmpdReg/src/client/DeleteLot.coffee, modules/CmpdReg/src/client/Dockerfile, modules/CmpdReg/src/client/ReparentLot.coffee, modules/CmpdReg/src/client/ReparentLotView.html, modules/CmpdReg/src/client/css/NewCmpdReg_nocompile.css, modules/CmpdReg/src/client/src/EditParent.js, modules/CmpdReg/src/client/src/MetaLot.js, modules/CmpdReg/src/client/src/Parent.js, modules/CmpdReg/src/client/src/ParentList.js, modules/CmpdReg/src/client/templates/EditParentSearchResultsView.inc, modules/CmpdReg/src/client/templates/EditParentSearchView.inc, modules/CmpdReg/src/client/templates/EditParentView.inc, modules/CmpdReg/src/client/templates/LotForm/ParentView.inc, modules/CmpdReg/src/server/routes/CmpdRegRoutes.coffee, modules/CmpdRegAdmin/src/server/routes/CmpdRegAdminRoutes.coffee
- Added reparent lot workflow to edit parent workflow for compound reg admins only
- If a structure is found by either the mol structure entered or by lot corp name an optional radio button is shown next to returned structures which allows the user to select the parent for reparenting.
- If a structure is selected, and alternative step 3 is shown to the user which shows the expected changes to the user including:
- Changed lot corp name
- Changed lot corp number
- Whether or not the parent is orphaned and will be deleted or not
- The experimental results which will by modified by the change
- The inventory results which will be modified by the change
ACAS-216
acas client tests
Ran manual tests via the UI
Verified that lots over the max auto lot threshold maintain their lot number on …
=> Reparent lot workflow editor ACAS-216-reparent-lot

modules/Components/src/client/OpenExperimentInQueryTool.coffee
**Original Steps to Reproduce**
- Upload an SEL file using the Experiment Loader.
- Click Generate Link
- Click Generate Link Again When Copy Link Button is Present 
**Original Observed Results**
The blue loading bar would extend beyond the grey summary box and would be aesthetically displeasing 
**Expected results:**
The blue loading bar should not extend beyond the grey summary box.
**Changed Behavior**
The Generate Link button is disabled after the first time the system successfully generates a link. This prevents the original UI bug from occurring since the loading bar should not be visible to the user for an extended period of time while the Copy Link button is also visible.
=> Generating Link Bar Overflows on Screen When Copy Link Button is Visible 

.github/workflows/docker-image.yml
- Switch from building every commit to branch to now only building on commits to `master` + `release/*` plus building on commits to PRs
Pushing to release branches: Will be tested after this is merged
Pull requests: Testing via this PR. See successful tests within "checks" on this PR.
Tags: Created tag 0.0.dev344 on acasclient and acas repos. See build: https://github.com/mcneilco/acas/runs/7528166639?check_suite_focus=true
=> ACAS-343: CI change to use corresponding acasclient version

modules/Login/src/server/routes/loginRoutes.coffee
- Some applications require 302 status and a location header set to /login when failing to login to ACAS, a change to the login routes returned 200 and did not set the location header
ACAS-389
Tested against and application that requires 302 and location header set and verified this fixed the issue of detecting a failed authentication.
Verified that normal UI login worked as expected.
=> Fix issue with detection of failed login for applications that require 302 and location

modules/Login/src/server/routes/loginRoutes.coffee
- /logout should redirect users to the configured base path, currently it's just redirecting to "/" which is LD
- Going to /logout/cmpdreg should redirect users to /cmpdreg
-  This is a feature added a long time ago to make links to /logout/cmpdreg easy to create
- The only known use case is for the excel apps we created which call /logout/excelApps when logging users out but its still a use case.
ACAS-390
Ran on Kubernetes instance of ACAS where login is /acas and verified logout takes you back to /acas
Ran on local instance of ACAS where login is / and verified logout takes you back to /
Ran /logout/cmpdreg on both K8s and local instance and verified login page is rendered with `After login you will be redirected to /cmpdreg` and you are then redirected back to K8s after login
=> Logout redirect to base path

modules/Login/src/server/routes/loginRoutes.coffee
- Applications using the ACAS api need a way to detect a failed login.  Instead of setting 302 and location /login. We should respond with a 401 and the login page.
ACAS-389
Verified that normal UI login worked as expected.
Verified that requesting /cmpdreg when logged out rendered `After login you will be redirected to /cmpdreg` and that after successful login, the user was redirected to /cmpdreg.
Verified logout worked as expected.
=> Set status code 401 when user is not authenticated and send the login page

modules/CmpdReg/src/client/src/MetaLot.js, modules/CmpdReg/src/client/templates/LotForm/MetaLotView.inc
- When re-using the same element like we do in meta lot, we need to stop listing to buttons events especially if we are listing for clicks old the same class name.
- This stop listing to any metalot events when creating the delete lot controller.
ACAS-393
With web inspector, verified that meta lot "downloadLot" function is no longer called when clicking "downloadLotButton" in Delete Lot view. Verified that DeleteLot controller "downloadLot" was called and that the sdf downloaded properly.
=> Fix issue with scoping button between deleteLot and metalot

modules/ExperimentBrowser/src/client/ExperimentBrowser.coffee, modules/ExperimentBrowser/src/client/ExperimentBrowserView.html, modules/ExperimentBrowser/src/server/routes/ExperimentBrowserRoutes.coffee
Made download button that given a current search and filter term, creates and downloads a zip for all files for matching experiments. 
* Created /exportExperimentFiles in ExperimentBrowserRoutes.coffee that takes an array of file names, creates a .zip file from them, and returns the .zip file name
- Created downloadFiles function in ExperimentBrowser.coffee that extracts all current experiments that pass filtering in the table sends array of their associated files to /exportExperimentFiles, downloads a .zip of the file and notifies user 
Created several experiments with different attachments, and attributes. Also deleted experiments to make sure that deleted experiment files weren't being included in the downloaded files.
=> Add bulk download button to Experiment Browser

modules/CmpdRegBulkLoader/src/client/CmpdRegBulkLoader.coffee, modules/CmpdRegBulkLoader/src/client/CmpdRegBulkLoader.html, modules/CmpdRegBulkLoader/src/server/routes/CmpdRegBulkLoaderRoutes.coffee
The "Has File Been Updated" column on the Purge Files window of the CReg Bulk Loader was loading to slowly. When moving this logic into another route, this caused the window to load slowly instead. The decision was made to hold off on adding this feature for the time being. 
Purge file window loads quickly without issue after removing "Has File Been Updated?" parts.
=> Removed all "has file been updated?" parts of CReg Bulk Loader

conf/config.properties.example, modules/CmpdReg/src/client/DeleteLot.coffee, modules/CmpdReg/src/client/src/MetaLot.js, modules/CmpdReg/src/server/routes/CmpdRegRoutes.coffee
Add new default config `client.cmpdreg.metaLot.disableDeleteMyLots` = `true` which disables deleting lots if the user is not a CregAdmin
ACAS-408
Ran acas client tests
Verified with setting on true, creg user who owned the lot could not see delete button
Verified with setting on false, creg user who owned the lot could see the delete and use the delete button
Verified with either setting a creg admin could see the delete and use the delete button
=> Add disableDeleteMyLots which dissallows anyone but cmpd reg users from deleting a lot

modules/GenericDataParser/src/server/generic_data_parser.R
**Steps to Reproduce:**
Load a string as a dose response value. e.g. "= 100" or "this is a string"
**Expected Results:**
Acas warns the user they have not provided a numeric value and that the curve may not render properly.
**Actual Results:**
ACAS throws an error:
```
Caught an error trying to validate dose response data. Please contact your administrator.: non-numeric argument to binary operator  
```
**Fix Description**
- If an uploaded curve parameters which is used to draw a curve is interpreted as string value the code was previously throwing this error which this code now fixes.
- It adds to the warning about missing dose response parameters that the provided value must be numeric.
The following **numeric** parameters were not found for curve id '1-1'. Please provide numeric values …
=> Test that provided parameters are interpreted as numeric

conf/config.properties.example, modules/ServerAPI/src/server/CustomerSpecificServerFunctions.coffee
- Switch to mapping specific group attributes to ls role configs which map the SSO group attribute to a system role
- Add `ROLE_CMPDREG-READONLY` to users able to login (can search creg but nothing else)
ACAS-394
Verified features of ACAS were added or removed by adding roles to a user one by one.
- Added user to acas-users group and verified they could login and see acas-user module menus but not admin or creg
- Added user to acas-admins group and verified they could see the addition acas admin module menus but not creg 
- Added user to cmpdreg-users and verified they could see creg but not creg admin
- Added user to cmpdreg-admins and verified they could see cmpd reg admin modules and bulk load admin purge app
- Revoked all roles except cmpdreg-readonly and verified I could login but …
=> SSO login map group attributes to ACAS roles

modules/Standardization/src/client/Standardization.coffee
Backporting fix for ACAS-405 (#987) to 1.13.7 release branch
This fix has been tested on 2022.1.x. No extra testing is planned.
=> ACAS-407: Backport critical kubernetes-relevant fixes to 1.13.7 release branch

modules/Components/src/client/OpenExperimentInQueryTool.coffee, modules/Components/src/client/UtilityFunctions.coffee
Added utility function to workaround Safari pop up blocker and used it in open experiment in query tool component.  This was technique being used in a few places but in slightly different ways:
https://github.com/mcneilco/acas/blob/ebc5cb75accb8f09ca249252685f76809b8d5696/modules/Standardization/src/client/Standardization.coffee#L75
https://github.com/mcneilco/acas/blob/65e0cdd4dc6a3fe920903c9a0652dcbfe79e1852/modules/ExperimentBrowser/src/client/ExperimentBrowser.coffee#L412
https://github.com/mcneilco/acas/blob/ebc5cb75accb8f09ca249252685f76809b8d5696/modules/Standardization/src/client/Standardization.coffee#L75
ACAS-426
Click the open in live design button in both chrome and safari and made sure pop ups weren't blocked.
This does not make it so you can repeatedly click the open in live …
=> Open url utility function which workaround safari pop up blocker

modules/Components/src/client/ACASFormFields.coffee, modules/ServerAPI/src/client/AttachFile.coffee
We have a few places that we're serving up URLs based on a filename, and we're not properly URI encoding, so the links are broken if the filenames have special characters like %.
This fixes it.
Patched this change in as javascript on a server demonstrating the issue, and confirmed it fixed the experiment file download link.
=> ACAS-427: add uri encoding for datafiles urls

modules/ServerAPI/src/server/routes/OpenExptWithQueryTool.coffee
I updated the function return signature of getUrlForNewLiveDesignLiveReportForExperimentInternal, and updated all but one location where the function is used.
This PR fixes the last usage to comply with the new function outputs.
Patched this in as javascript onto an instance demonstrating the issue, and confirmed it fixes the issue.
=> ACAS-424: Fix Open In LiveDesign button on Experiment Editor

modules/ServerAPI/conf/ProtocolConfJSON.coffee, modules/ServerAPI/src/client/Experiment.coffee, modules/ServerAPI/src/client/Experiment.html, modules/ServerAPI/src/client/Protocol.coffee, modules/ServerAPI/src/client/Protocol.html
I started to work on the rendering piece, and made some progress. I wanted to give you a chance to review this before shoving it all into your branch. I think this would be good to merge in tomorrow morning so we can build on top of it.
Tested locally that the "Add Endpoint" button in Protocol Editor still works
Tested viewing experiments both in Experiment Browser and Protocol Browser.
There's a known issue that the "units" dropdown starts out empty. I tested that I could use the "editable picklist" to add values to the database, and then they'd be correctly rendered when viewing saved experiments. But long term we'll need to change the backend logic to save these during the data loading, so it's OK to ignore this for now.
=> ACAS-412: Partial work on rendering data column values within Experiment

.github/workflows/tagger.yml
Creates a manually-triggered workflow that applies a git tag to a branch across all ACAS repos
Not tested yet, needs to be merged before it can be tested.
=> ACAS-362: Make a manually triggered workflow to apply the same tag on all ACAS repos

.github/workflows/tagger.yml, .github/workflows/trigger-tag.yml
This adds a second workflow "Trigger Dev Tag" that will figure out the next ".dev" tag, then call the "Tag ACAS Repos" workflow. The idea is to put this "Trigger Dev Tag" workflow onto every acas repo, so a commit to a release branch on any repo will trigger a new tag on every repo.
Not tested yet, need to merge to test.
=> ACAS-362: automate dev build tagging

modules/BuildUtilities/src/server/routes/RequiredClientScripts_template.js, modules/ChemStructure/src/server/routes/ChemStructureRoutes.coffee, modules/CmpdReg/src/server/routes/CmpdRegRoutes.coffee, modules/Components/src/client/ACASFormChemicalStructure.coffee, modules/Components/src/client/ACASFormChemicalStructureView.html, modules/ServerAPI/src/client/SaltBrowser.coffee, modules/ServerAPI/src/client/SaltBrowser.html
Switch Salt Browser sketcher to actually use Maestro sketcher when client.cmpdreg.sketcher = 'maestro', then fix a couple issues with instantiating the sketcher and getting & setting mols.
Tested locally by coping maestro sketcher code into dev environment, then ran with maestro sketcher configured. Confirmed I could register a salt, got the correct molecular weight and formula, could render the images, and the "edit salt" workflow started with the correct structure loaded in the sketcher.
In this local dev setup, I did observe an issue where the structure image wouldn't render during the "preview" phase before save. This appears to be a MOL V3000 issue with the indigo / cdk rendering code in Roo. 
```
acas-roo-1  | 06 Sep 2022 18:39:55 72605 [http-nio-8080-exec-3] ERROR …
```
=> ACAS-6: Fix Maestro sketcher implementation

modules/ServerAPI/src/client/SaltBrowser.html
**Steps to reproduce:**
As a CReg admin, navigate to the CmpdRed Salts panel, pick any salt from the table and edit it.
**Previous:**
Too much line spacing between the sketcher and the fields beneath it. 
**Changed:**
Even spacing across the panel with not too much real estate occupied.
=> Removing Unnecessary Spacing in Salt Edit Panel 

modules/BuildUtilities/src/server/routes/RequiredClientScripts_template.js, modules/Components/src/client/ACASFormFields.coffee, modules/Components/src/client/ACASFormStateTable.coffee, modules/Components/src/client/PickList.coffee, modules/ServerAPI/src/client/Protocol.coffee
I took a sortof extreme approach to this, and tried to alter the EndpointController to use the ACASFormStateTableFormController, which was built to create a non-tabular layout, but still save values to a StateTable data structure.
It took a bunch of troubleshooting, but I was able to get that working with some minor tweaks to ACASFormFields and ACASFormStateTable and Protocol. With that, I was able to shift from our bespoke controllers into a more "LsThing-like" mode where we can configure `EndpointsValuesConf` and derive the fields from there.
The big advantage here is that we can then take advantage of pre-existing code that works properly for saving these values. I briefly had an issue where I was saving _two_ new values every time I made an edit, but I was able to track that down to …
=> ACAS-304: Bugfix for saving issue

modules/GenericDataParser/src/server/generic_data_parser.R
Present an error to the user if they upload Number values in experiment loader which are interpreted as Infinite.  Specifically, when the user uploads "Inf" or "-Inf".
ACAS-449
Added acasclient test for experiment loader files with Inf and -Inf Number values
=> ACAS-449: Inf numeric values uploaded  to experiment loader should produce and error

modules/ServerAPI/src/client/SaltBrowser.coffee
Okay button is part of another HTML element being shown/hidden so using .show()/.hide() on this specific button is not necessary
**Steps To Reproduce**
Edit a Salt in the Salt Browser. Go through the whole workflow so you end up back at the salt browser.
**Prior Bug Results**
There's a red "Okay" button below the browser results table which sticks around through any new actions you take in that module. 
**Fix Results**
Salt browser shows the same way as before your edit.
=> RM show() Edit Salt Okay Button

conf/config.properties.example
Change default for `server.service.projects.restrictExperiments` to `true`
This restricts experiments in experiment search to only those the user has project acls for.
ACAS-461
Ran ACAS client tests.
=> ACAS-461: Change default server.service.projects.restrictExperiments to true

modules/CmpdRegBulkLoader/src/client/CmpdRegBulkLoader.coffee, modules/CmpdRegBulkLoader/src/client/CmpdRegBulkLoader.html, modules/CmpdRegBulkLoader/src/server/routes/CmpdRegBulkLoaderRoutes.coffee, modules/Components/src/client/LSFileChooserView.html
ACAS introduces spaces and numbers in parentheses to keep SDF and zip filenames distinct because it drops them all into a common privateUploads folder. This makes life harder for users who may upload the same file multiple times but get different filenames when they re-download that same file from ACAS, or when they download derived zipfiles.
This acas change adds an "originalFileName" variable which is tracked and passed to the roo layer. Across the validation, registration, and purge pages, these changes make it so we show the original filename (`example.sdf`) and download as the original filename (`example.sdf`), but href to the correct filename (`example (26).sdf`) in cases where the same filename has been uploaded many times.
These changes are co-dependent with …
=> ACAS-271: Preserve file naming in SDF bulk loader

modules/Components/src/client/ACASToast.coffee, modules/ModuleMenus/src/client/ModuleMenus.coffee
Heart beat monitor which checks every 10 seconds for a disconnection or logout of ACAS and displays a message.
If the message is already being shown and the status does not change then the message is left
If the status changes (either a successful connection or not) the message is removed or change to match the current status.
ACAS-466
Logged into ACAS and restarted the backend and verified a message about not being able to communicate with ACAS showed.
Once ACAS restarted but the user was logged out, verified the message was updated to match new "logged out" status.
Logged back in via another tab and verified that the message went away.
=> ACAS-466: heart beat monitor in ui

modules/CmpdRegBulkLoader/src/server/routes/CmpdRegBulkLoaderRoutes.coffee
Fall back to the required fileName key when registering an SDF file
ACAS-271
Ran acasclient tests.
=> ACAS-271: Fallback for when register request is missing originalFileName

modules/CmpdReg/src/client/CmpdReg.jade, modules/CmpdReg/src/client/css/NewCmpdReg_nocompile.css, modules/CmpdReg/src/client/src/EditParent.js, modules/CmpdReg/src/client/src/RegistrationSearch.js, modules/CmpdReg/src/client/src/Salt.js, modules/CmpdReg/src/client/src/SaltForm.js, modules/CmpdReg/src/client/src/SearchForm.js, modules/CmpdReg/src/client/templates/LotForm/NewSaltView.inc, modules/CmpdReg/src/client/templates/LotForm/ParentView.inc, modules/CmpdReg/src/client/templates/RegistrationSearchView.inc, modules/CmpdReg/src/server/routes/CmpdRegRoutes.coffee, modules/Components/src/client/ACASFormChemicalStructure.coffee, modules/Components/src/client/UtilityFunctions.coffee, modules/ServerAPI/src/client/SaltBrowser.coffee
- Refactor CmpdReg to use ACASFormChemicalStructure class
- Add utility function to get the system configured sketcher (Maestro, Marvin or Ketcher)
- Add "clear" functionality to ACASFormChemicalStructure
- Fix jchem getMol in ACASFormChemicalStructure
- Make getMol and async/await function
* this does not yet fully fix ACAS-469 to update to the new maestro API, this was just to get all the logic of the chemical sketcher usage to use ACASFormChemicalStructure
ACAS-469
Ran through compound registration, search, edit parent and salt creation workflow in creg
Ran through salt browser editing and creation
=> ACAS-469: Refactor creg to use ACASFormChemicalStructure.coffee

modules/CmpdReg/src/client/CmpdReg.jade, modules/CmpdReg/src/client/css/NewCmpdReg_nocompile.css, modules/CmpdReg/src/client/schrodinger/maestrosketcher/maestrosketcherlauncher.js, modules/CmpdReg/src/client/src/EditParent.js, modules/CmpdReg/src/client/src/RegistrationSearch.js, modules/CmpdReg/src/client/src/Salt.js, modules/CmpdReg/src/client/src/SaltForm.js, modules/CmpdReg/src/client/src/SearchForm.js, modules/CmpdReg/src/client/templates/LotForm/NewSaltView.inc, modules/CmpdReg/src/client/templates/LotForm/ParentView.inc, modules/CmpdReg/src/client/templates/RegistrationSearchView.inc, modules/CmpdReg/src/server/routes/CmpdRegRoutes.coffee, modules/Components/src/client/ACASFormChemicalStructure.coffee, modules/Components/src/client/UtilityFunctions.coffee, modules/ServerAPI/src/client/SaltBrowser.coffee
- To be reviewed after https://github.com/mcneilco/acas/pull/1019
- Updates the maestro sketcher usage to handle newer versions of maestro sketcher
- sketcherImportText became sketcher_import_text
- sketcherExportText became sketcher_export_text
- sketcher_export_text takes an additional parameter to export a mol
ACAS-469
Ran through compound registration, search, edit parent and salt creation workflow in creg
Ran through salt browser editing and creation
=> ACAS-469-maestro-sketcher-update

modules/CmpdReg/src/server/routes/CmpdRegRoutes.coffee
Get lot ACLs is currently broken for registeredBy users.  Instead of checking for registedBy, we are checking for a non-existent recordedBy attribute.  This causes users who registered a lot but aren't cmpdreg admins, or the "chemist" of the lot to be able to edit their own lots.
ACAS-482
Configured a lot and permissions such that I reproduced the bug and could not edit a lot that was registeredBy me.
Updated the code and refreshed the page and verified I could not edit the lot.
Switched the registedBy user to another user and verified I could no longer edit the lot. (negative case test).
=> ACAS-482 fixing registerdBy ACLS permissions

modules/CmpdRegBulkLoader/src/client/CmpdRegBulkLoader.coffee
- I'd forgotten to check this change in on my last PR. This fixes the display name and downloaded file name for the link shown _after_ you purge a file
Local UI testing, confirmed acasclient tests pass this time. Added more acasclient tests for originalFileName in https://github.com/mcneilco/acasclient/pull/100
=> ACAS-271 followup: Fix download link after purging file

.github/workflows/trigger-tag.yml, modules/Components/src/client/ACASThingBrowser.coffee, modules/Components/src/client/ACASThingBrowserView.html, modules/ServerAPI/src/client/ExampleThing.coffee, modules/ServerAPI/src/server/ControllerRedirectConf.coffee
- Use new "flat" advanced search returns and on click of a row, fetch the full ls thing object
- Fix issue with dates values rendering as Nan-na-na
- Fix issues with Search messages not rendering properly
- Add notification of when max search results has been hit
ACAS-460
ACAS client tests of new roo route changes
Manual testing of ACASThing browser with 10,000 things, clicking on rows, hitting max limit...etc.
=> ACAS-460 LsThingBrowser use flat advanced search results, fix hiding/showing of messages

modules/Standardization/src/client/Standardization.coffee
- Allow the user to limit the download sdf results by passing the max results input to the service
ACAS-488
Clicked download and verified the results were limited
Removed the input and verified that the results were not limited by max results
=> ACAS-488: Allow user to limit by max results input

modules/Standardization/src/client/Standardization.coffee
- Changes to the UI to match the service changes.
-  Parent is now added to the response json with corpName and molWeight as attributes instead of being top level
- Use delta mol weight calculated by the server to keep logic in one place
Changes. to be merged in only when closing ACAS-480-epic branch.
ACAS-486
Ran queries and made sure UI looked correct for delta mol weight, old mol weight and corp name fields and that structures rendered in the UI (as they use the corp name returned to fetch images).
=> ACAS-486: Standardization dry run UI change to go with service changes

conf/config.properties.example, modules/CmpdReg/src/server/routes/CmpdRegRoutes.coffee, modules/Standardization/src/client/Standardization.coffee, modules/Standardization/src/client/Standardization.html
For cmpd reg standardization
- Add Settings Valid true/false to Current Settings panel
- Add Settings Invalid Reasons list to Current Settings panel
- Add Needs standardization true/false to Current Settings panel
- Add Reasons for needing standardization to Current Settings panel
- Add Suggested configuration changes to Current Settings panel
- Updated message in Creg and bulk Loader to reflect the invalid settings and needs standardization state
ACAS-387
**Changed the standardization settings to be in an invalid state and changed the hash scheme to make it so it required restandardization.**
**Verified the CmpdReg standardization module showed the appropriate messages and the the dry run  was disabled:**
**Verified both creg and bulk load displayed the appropriate message:**
**Removed …
=> ACAS-387: Add reasons for standardization needed

modules/CmpdReg/src/client/schrodinger/maestrosketcher/maestrosketcherlauncher.js, modules/Components/src/client/ACASFormChemicalStructure.coffee
- MaestroJSUtil was missing a check for the older `sketcherExportMolBlock` to be backwards compatible with older maestro sketchers
ACAS-469
Updated a server running older maestro sketcher and verified the sketcher loaded.
=> Fix backwards compability with older maestro sketcher versions which used sketcherExportMolBlock

.github/workflows/docker-image.yml, .github/workflows/tagger.yml, .github/workflows/trigger-tag.yml, .gitignore
Fixing warnings:
- Bump `docker/*`, `setup-python`, and `github-script` action versions to fix Node 12 deprecation warnings
- Replaced set-output based on https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
A few small unrelated changes:
- Applied a fix for sorting git tags (`--sort=v:refname` rather than `--sort=committerdate`) that I'd applied to acas-roo-server and racas but forgot to apply to acas
- Removed `.github` from gitignore because we do want to track the workflow files in there
Tested via this PR.
Latest run has no warnings: https://github.com/mcneilco/acas/actions/runs/3389274203
=> ACAS-491: GitHub actions fix deprecation warnings

modules/CmpdReg/src/client/MultipleFilePicker/css/style_nocompile.css, modules/CmpdReg/src/client/MultipleFilePicker/javascript/src/file.js, modules/CmpdReg/src/client/MultipleFilePicker/templates/DropView.inc, modules/CmpdReg/src/client/MultipleFilePicker/templates/jspVersion/file_template_desc_jsp.inc
ACAS-498 adds a new "Writeup" text field associated with each analytical file attached to a Lot in CReg. The purpose of this is to store standard NMR and LCMS writeup information (https://pubsapp.acs.org/paragonplus/submission/acs_nmr_guidelines.pdf) used in publications, alongside the corresponding pdfs and raw data.
The frontend portion here adds the new `textarea` to the form, makes sure it is saved and rendered properly, and tweaks some styling so that saved and new rows line up properly. See screenshot below.
Tested locally that I can upload and save an analytical file with a writeup. Confirmed that it's rendered properly when the page is reloaded after save.
=> ACAS-498: Add Writeup field to CReg analytical files

modules/CmpdReg/src/server/routes/CmpdRegRoutes.coffee
**Steps to Reproduce:**
With the setting to disallow duplicate aliases turned on. Try and edit a parent alias to match a parent alias that exists on another compound already.
**New Results:**
The UI displays an error to the user stating that:
Parent Aliases must be globally unique.
**Previous Results:**
No error is shown and the UI hangs
Manually checking steps provided in ticket. See Screenshot...
=> Bug Fix: Duplicate Parent Alias Errors Don't Bubble Up To UI

modules/Components/src/client/ACASFormFields.coffee, modules/GenericDataParser/src/server/generic_data_parser.R, modules/ServerAPI/conf/ExperimentConfJSON.coffee, modules/ServerAPI/src/client/Protocol.coffee
For the endpoint manager, the items in the "data column order " state have been saved with "stringValue" types when they should be saved with "codeValue" types to follow ACAS's standards.
Changed the following values from "stringValue" to "codeValue", and set the "codeType", "codeKind", and "codeOrigin" attributes accordingly in Frontend Protocol/Experiment endpoint tables and Backend R logic (genericDataParser):
- column name
- column conc units
- column time units
- column units
- column type
- hide column
- condition column
- Used experiment loader to upload experiment to see if the experiment and new protocol values were stored as codeValues and if the values were displayed in the endpoint table
- Also tested by manually creating a new protocol
=> Switch "data column order" stringValues to codeValues

modules/CurveAnalysis/src/client/CurveCuratorAppController.coffee, modules/CurveAnalysis/src/client/CurveCuratorAppView.html, modules/GenericDataParser/src/server/generic_data_parser.R
**Extra Context** 
The efforts to DRY the "Open In" button feature with 
OpenExperimentInQueryTool was not applied to the button in Curve Curator. It was added to the Experiment Browser and the Experiment Loader but forgotten here. 
**Steps to Reproduce:**
Load a Dose Response formatted file into ACAS using the Dose Response module
Open the data set in Curve Curator
Click the Open In LiveDesign button
**Previous Bug Results:**
Browser opens a new tab but Live Design never opens
**Fix Results:**
LiveDesign opens to a Live Report with the expected data
=> Bug Fix: Open in Livedesign Button Broken in Curve Curator

modules/CmpdReg/src/server/routes/CmpdRegRoutes.coffee
- Fix misspelled registeredBy
- This is a fix for the already closed out https://github.com/mcneilco/acas/pull/1038 which had the name misspelled.
ACAS-482
Configured a lot and permissions such that I reproduced the bug and could not edit a lot that was registeredBy me.
Updated the code and refreshed the page and verified I could not edit the lot.
Switched the registedBy user to another user and verified I could no longer edit the lot. (negative case test).
=> ACAS-482: Fix misspelled registeredBy

modules/GenericDataParser/src/server/generic_data_parser.R
**Expected Results:**
ACAS errors and the endpoints never show up in the endpoints dropdown list because the experiment was never successfully loaded
**Actual Results:**
ACAS errors as expected, however the endpoints are listed in the endpoints dropdown
**Fix:**
- Added logic to the validateExperimentColumns() function so that it returns TRUE/FALSE if the experiment did not pass strict endpoint matching requirement. 
- Added logic so endpoints are only saved if the experiment is creating a new protocol or passes the strict endpoint matching requirement 
Tested with the files used in reporting the bug (file-1.csv, file-2.csv). 
**Before ("Clint Eastwood" endpoint saved when it should not be)**
**After (No "Clint Eastwood" endpoint saved)**
=> Endpoints should not be added during failed uploads to ACAS

modules/ServerAPI/src/client/Experiment.coffee, modules/ServerAPI/src/client/Experiment.html, modules/ServerAPI/src/client/Protocol.html
The endpoint table in the Experiment editor did not have an explanation. Added text and formatting for explaining the endpoint table.
Tested locally.
=> Adding description/explanation to Experiment Endpoint table

modules/Components/src/client/ACASFormFields.coffee, modules/GenericDataParser/src/server/generic_data_parser.R, modules/ServerAPI/src/client/Protocol.css
Fixed fields in the endpoint manager that were not aligned. 
Tested on endpoint table to see if fields were aligned. 
After:
=> Textbox alignment in endpoint manager

modules/Components/src/client/ACASFormFields.coffee, modules/GenericDataParser/src/server/generic_data_parser.R
ACAS was giving the following error when uploading some experiment files. 
The error occurred in experiment files empty values for units that could not be saved when the codes were saved to the database. The issue was resolved by adding handling for empty values when saving codes. 
Also fixed an issue where some objects would not render since they had a null value. 
Reloaded the same files that were previously throwing the error and saved them successfully. Uploaded multiple times by editing protocol to include and not include the endpoints, and tried with strict endpoint enabled and disabled to make sure strict endpoint matching worked correctly.
=> Fixed internal error when uploading some experiment files to ACAS

modules/ServerAPI/src/server/python/acas_ldclient/acasldclient.py
- Fix bad comparison of boolean to string
- Add logging to acasldclient
ACAS-514
Tested on a properly configured server where CustomerSpecificServerFunctions.coffee hadn't been modified to pass string "true" to get_user function.
Watched the logs and verified properly logging.
=> ACAS-514: Follow up fix for acasclient.py ACAS_ONLY_ACL_ group permissions

modules/GenericDataParser/src/server/generic_data_parser.R
- Aggregate identical stat threshold warnings and missing parameters warnings
- I removed the actual value of the stat violation but that stat value and highlighted yellow warning can also be viewed in the dose response table
- Add high priority warnings which move the warning to the top of the list
ACAS-525
Ran acas client tests and UI test
=> ACAS-525: Aggregate some dose respone warnings, high priority experiment reload warning

modules/CmpdReg/src/server/routes/CmpdRegRoutes.coffee
ACAS-507 is meant to open the "Edit Parent" workflow up via acasclient. While doing so, I realized that the two routes used in edit parent, as well as the swapParentStructures endpoints are accessible to any CReg user. Both Edit Parent and Swap Structures should only be accessible to CReg admins. This PR makes this the case.
ACASClient testing in this PR: https://github.com/mcneilco/acasclient/pull/104
=> ACAS-507: Lock down edit parent and swap structures endpoints to CReg Admins

modules/CurveAnalysis/src/server/renderCurve.R
**Steps to Reproduce:**
- Load a dose response file into ACAS
- Grab a curve id using the following query `select curveid from api_curve_params limit 1;`
- Render the curve URL:
http://localhost:3000/api/curve/render/dr?curveIds=AG-00000017_3&colorBy=protocol
**Expected Results:**
The plot renders with the protocol name like this:
**Actual Results:**
The plot renders but the curve ID (an random identifier) is shown in the plot
**Additional info:**
Also affected by this bug would be plotting flat curves for inactive or highly active curves when fit using the ACAS dose response fit (would not apply to curves just uploaded without an ACAS curve fit)
ACAS-565
Verified that legend shows the correct text when set to batch, protocol or experiment and shows the curve id when colorBy is not given …
=> ACAS-565: Fix curve render color by

docker-compose.yml
Local dev environment java debugging stopped working with Java 11 upgrade.
Found an easy fix: See https://www.baeldung.com/java-application-remote-debugging#from-java9
- Confirmed I can attach a debugger after making this change
=> Regain debugger attachment on java 11

conf/config.properties.example
The major new feature of protocol endpoint management was feature flagged / disabled by default, but it is now ready enough that it should be enabled by default.
N/A
=> ACAS-304: enable protocol endpoint manager by default.

conf/config.properties.example
The endpoint manager feature is ready for prime time testing, so it should be on by default.
For current python tests to pass, strict matching default must be false. This is also the "least breaking change" behavior, so it is a sensible default.
Local unit tests, will also be watching the CI tests on this PR
=> ACAS-574: Enable endpoint manager by default

modules/ServerAPI/src/server/routes/ExperimentServiceRoutes.coffee
Checks for projectCodes query parameter in experiment search route
Passes the intersections of allowed projects and requested projectCodes to persistence layer for filtering experiments by project
ACAS-575
Ran acasclient tests
=> ACAS-575: Add parameter to experiment search to filter by project code

modules/CmpdReg/src/server/routes/CmpdRegRoutes.coffee
Checks for projectCodes body parameter in cmpdreg search route
Passes the intersections of allowed projects and requested projectCodes to persistence layer for filtering cmpds by project
acasclient tests
=> ACAS-576: Adds projectCodes filter to cmpdreg search

modules/CmpdReg/src/server/routes/CmpdRegRoutes.coffee
- Fix for blocking registration when system needs restandardization
ACAS-580
Deployed updated code to a server which should have been blocking registration and verified this fixes the issue.  Ran standardization and verified the user message message and blocking went away.
=> ACAS-580: Fix for blocking registration in UI

modules/ServerAPI/src/client/Experiment.coffee
When the experiment status in the experiment editor was changed from "Approved" or "Rejected" to "Created"/"In Process"/"Complete", the fields in the endpoint table were editable when they should not be editable in the experiment editor. 
This was being caused by logic that would enable or disable all fields in the page when the status was changed from a locked status ("Approved"/"Rejected") to an unlocked status ("Created"/"In Process"/"Complete"). 
To fix this, I added some lines to the function that handles when the status is changed that will always disable the endpoint table fields (I brought a copy of the function from BaseEntityController so that I wouldn't change anything universally). 
Tested it by toggling between the different statuses of an experiment. …
=> Endpoints are editable under Experiment Editor when Experiment is in "In Process" status

modules/Standardization/src/server/routes/StandardizationRoutes.coffee
- Fixes passing invalid characters in URL to roo
roo gave this error before:
```
acas-roo-1  | 25-Jan-2023 19:13:24.479 INFO [http-nio-8080-exec-1] org.apache.coyote.http11.Http11Processor.service Error parsing HTTP request header
acas-roo-1  |  Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
acas-roo-1  |   java.lang.IllegalArgumentException: Invalid character found in the request target [/acas/api/v1//standardization/execute?username=bob&reason=[] ]. The valid characters are defined in RFC 7230 and RFC 3986
acas-roo-1  |           at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:494)
acas-roo-1  |           at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:271)
acas-roo-1  |           at …
```
=> ACAS-593 URL Encode the reason for standardization when passing to persist layer

modules/CmpdReg/src/client/src/MetaLot.js, modules/CmpdReg/src/client/src/NewLotSuccess.js, modules/CmpdReg/src/client/src/Search.js, modules/CmpdReg/src/client/src/SearchResults.js
When adding a new lot, the  compound ID that gets copied over includes the lot suffix which results in the 'Next Step' failing (see screenshot).
If the lot suffix is dropped then the subsequents steps function as normal. 
This fix includes code to drop the lot suffix and prevents it from being copied over whenever a "New Lot" button is utilized. 
The second step now is successful. 
NOTE: This previously worked on an environment where ACASLabelSequences is not utilized. 
Manually
=> Bug Fix: Adding New Lot Copies Lot Corp Name and Causes Error in Subsequent Search Query 

modules/ExperimentBrowser/src/client/ExperimentBrowser.coffee, modules/GenericDataParser/src/server/generic_data_parser.R, modules/ServerAPI/conf/ExperimentConfJSON.coffee, modules/ServerAPI/src/server/routes/ExperimentServiceRoutes.coffee
Users often are hampered by apparent 'missing data' when a registrar fails to update the experiment name field.  A new experiment code is generated and the previous ACAS file-data is replaced (overwritten).  In most cases, the current behavior is desired, since it allows trivial adjustments to units, endpoint labels, etc.  But in wrong hands it leads to a confusing state.  Moreover, as registrars it is difficult to even discover such cases and troubleshoot.  Here we want to enhance the Experiment Browser table such that it can be used to recover from such registration failures. 
Scope of This Work 
- Adding "Overwritten" as an "Experiment Status"
- Show Overwritten Experiments in Experiment Browser if the user has client.entity.viewDeletedRoles
- Adding a route in the delete experiment …
=> Improving Reporting of Overwritten Experiments 

modules/GenericDataParser/src/server/generic_data_parser.R
When an experiment with new column units was uploaded and had an existing protocol, the units were not present in the endpoint table when the experiment was viewed in the experiment browser/editor. 
This was being caused because codetables for new column data were only saved to the database in the case that the experiment was associated with a new protocol. To fix, logic was moved so that codetables would be saved on any valid experiment load. 
Tested by loading an experiment with new column units against an existing protocol. Units were displayed in the experiment when viewed in the experiment browser/editor.
=> Units in experiment endpoint table are not loading

modules/ServerAPI/src/client/Protocol.coffee
In the protocol endpoint manager, users should be able to click on a row in the endpoint table find experiments using that protocol that have columns with the corresponding data. 
It was observed that when using this search feature some experiments that should have been showing up in the results were not, and conversely, experiments that should not be showing up were. This was being caused by logic that was not clearing the variables used to see if values matched between searches. The error was fixed by resetting variables each round of searching. 
Tested locally with a set of experiments with different units, column names loaded on one protocol to see if searches would load the correct set of experiments.
=> Experiment search in endpoint manager not filtering properly

modules/Components/src/client/BasicFileValidateAndSave.coffee, modules/Components/src/client/LSFileChooser.coffee, modules/Components/src/client/LSFileChooserView.html, modules/GenericDataParser/src/client/GenericDataParser.coffee
Instructional text for 'Load Experiment' says to 'select a file', but the file-browser GUI is multi select. This has caused issues where users may think they are uploading many experiments but are only uploading one. 
To fix this, the "Browse Files..." button only allows users to select one file while uploading. Since users can also drag and drop multiple instead of using the "Browse Files..." button, logic was put in place to block validation when multiple files are trying to be uploaded. A error message explains that only one file can be uploaded at a time when this is attempted. 
Tried to use the "Browse Files..." button to select multiple files (no longer possible). Dragged and dropped multiple files and tried to upload them and saw that validation/upload was blocked. Subsequently …
=> Mismatch between load experiment instructions and browse select behavior

modules/ServerAPI/src/client/Protocol.coffee
In the protocol endpoint manager, endpoint rows are disabled whenever the endpoint is in use by an experiment to prevent discrepancies from occurring. However, it was noticed that the endpoint rows were still disabled when all experiments associated with the protocol using the endpoint were deleted.
This was because there were no steps to ensure that deleted and ignored experiment endpoints were not being considered by the logic that was used to disable the rows. To fix this, a step was added to filter out deleted and ignored experiments. 
Replicated the original issue locally by uploading a protocol, deleting the experiments and seeing if the rows in the protocol endpoint manager were now enabled (which they were).
=> Endpoint rows are still disabled after experiments are deleted

modules/ServerAPI/src/server/routes/ProtocolServiceRoutes.coffee
It was observed that the "Download Template" button in the protocol browser and protocol editor was not working. 
This was caused by logic when creating the .csv template file that could not handle instances where the protocol did not have a project assigned. To fix, logic was added to handle cases where there was no project for a protocol. 
Tested locally with protocols where the "Download Template" button was not previously working and now worked with the added logic.
=> Download Template button in protocol browser/editor not working

modules/ServerAPI/src/server/routes/ProtocolServiceRoutes.coffee
After downloading template SEL files in the protocol browser/editor, there are issues with loading the file into pandas since the .csv is formatted incorrectly due to extra commas that should not be there in the Experiment Meta Data section. Additionally, uploading the file to ACAS after editing would fail due to a typo where "Experiment Meta Data" was "Experiment Metadata". To fix, extra commas were removed and the typo was corrected. 
- Downloaded template SEL file, added data and re-uploaded it into ACAS in both .xlsx and .csv formats
- Used the following code to test if the .csv was formatted properly and both sections could be loaded into pandas: 
```python
import pandas as pd
filename = "download - 2023-02-15T130655.658.csv" # downloaded SEL template file 
df = pd.read_csv(filename, …
```
=> SEL template files not properly formatted

modules/CmpdRegBulkLoader/src/client/CmpdRegBulkLoader.coffee, modules/CmpdRegBulkLoader/src/client/CmpdRegBulkLoader.html
When trying to purge a very large CmpdReg bulk load file, the UI should wait until the file is purged but it has been reporting an error while the file is still purging. This is due to a timeout after 30 seconds. To fix, I set the ajax request timeout to zero so it would not timeout while purging. 
To recreate and test the issue:  
- Bulkloaded a small file
- Hooked up the debugger to roo and put a breakpoint here:
https://github.com/mcneilco/acas-roo-server/blob/d32a885cbee71d3099e1a8a9faaf4e941536e54c/src/main/java/com/labsynch/labseer/service/BulkLoadServiceImpl.java#L2531
- In the UI, click purge
- Wait 30 seconds to reproduce the issue as the breakpoint pauses roo and mimics the long purge time.
Before the fix, an error was thrown after 30 seconds. Afterwards, it would hang for …
=> Bulkloader purge timeouts after 30 seconds

modules/CmpdReg/src/server/routes/CmpdRegRoutes.coffee, modules/ServerAPI/src/server/routes/ExperimentServiceRoutes.coffee, modules/ServerAPI/src/server/routes/ProtocolServiceRoutes.coffee
I have [acas-roo-server: PR](https://github.com/mcneilco/acas-roo-server/pull/422) and [acas: PR](https://github.com/mcneilco/acas/pull/1078) to add more experiment information to the linked experiments of a Lot but I think I could have done it more simply by querying and adding the fields in the acas layer instead of writing specific SQL queries and creating DTO for the data format.
Note:
If we would want the same information to be available across all usages of the `CmpdRegBatchCodeDTO` then it would be reasonable to add all the information in the acas-roo layer but I thought of trying this and getting feedback.
- I have refactored the code to create a separate function that handles ACLs and adds protocol and analysis group information to the experiment object.
- I fixed a bug with …
=> Add protocol and analysis group codes to experiments linked to a lot.

modules/ServerAPI/src/server/routes/FileServices.coffee
- Fixes: The "Browse Files..." button for the query-file-upload wasn't being re-enabled after we started setting maxNumberOfFiles in https://github.com/mcneilco/acas/pull/1072
-   The jQuery file plugin (which we have customized) requires a `delete_type` and `delete_url` returned from the server when uploading a file or it will not reset the maxNumberOfFiles when you click delete.
- To fix this I added:
- The `delete_url` and `delete_type` to our upload route
- A no-op delete route to data files (Didn't implement actual delete because there are lots of implications we have not fully though through yet.
ACAS-612
Ran through the UI process for uploading an experiment file (refreshed between each bullet point)
- Upload file, validate, save, load another, (had to click delete file but I think …
=> ACAS-612: Provide delete_type and delete_url and noop delete file route

bin/acas.sh
- At some point the check to see if persistence layer was up started failing i.e. `curl --output /dev/null --silent --head --fail http://${client_service_persistence_host}:${client_service_persistence_port}` returned a fail (status code over 404).  I believe this was when roo was removed
- This led to intermittent failures of ACAS login on a fresh system as `PrepareModuleConfJSON.js` wouldn't run
- The fix was to:
- Have the curl call the protocol types endpoint in the persistence layer to check it is up (returns 200 code)
- Don't have a wait timeout and just keep running the loop while roo is not up
- Print to the logs the current status of the script to make it more obvious when it is failing
ACAS-638
- Started up a fresh instance and verified the logs looked correct:
```
[acas] …
```
=> ACAS-631: Fix wait for persistence in acas.sh

modules/ProtocolBrowser/src/client/ProtocolBrowser.coffee, modules/ProtocolBrowser/src/client/ProtocolBrowser.html, modules/ServerAPI/src/client/Protocol.coffee, modules/ServerAPI/src/server/routes/ProtocolServiceRoutes.coffee, package.json
Users of the protocol endpoint manager asked how well the template download feature could handle special characters. To test it, a string of special characters (@"|!#$%&/()=?»«@£§€{}.-;'<>_,") was inserted in different parts of a protocol that was uploaded. When trying to download the template of this protocol, the file was truncated in the middle of the string: 
In order to fix, the template file .csv construction was refactored to use the csv-stringify library instead of manually constructing the .csv string. The frontend was also updated to handle the new format. 
A minor bug where the warning/success text for "Download All Files" would also show when hitting the "Download Template" button from the text divs sharing the same class name was fixed as well. 
Tested with the same protocol …
=> Add special character handling to SEL template file download

.github/workflows/upmerge.yml
**Background**
ACAS has several repositories and may have multiple release branches at a given time.
Keeping track of branches to unmerge is prone to mistakes and forgetfulness so lets automate it.
**Implementation**
Loops through protected branches of the acas, acas-roo-server, acasclient and racas repos and creates pull requests to upmerge them if there are any commits between them.
- It assigns the PRs to the latest commit author
- It adds all authors as reviewers to the PR
- The PRs are created by the api user (currently frost) so he must be excluded from the reviews as GitHub doesn't allow you to review your own PR.  If the api user is in the list of authors, I just tag the user in the description of the PR (see example)
*Example pr: …
=> ACAS-640: Create upmerge pull requests github action

modules/ServerAPI/src/server/routes/ProtocolServiceRoutes.coffee
When downloading an SEL file for a protocol with multiple experiments, I observed that random time values were being inserted into the template that were not in any of the experiments or in the protocol endpoints. Even more strangely, the values would be associated with different endpoints and have different values each download. 
The error was coming from a line in the template file generating logic for endpoint time, where a single `=` was used instead of a `==`, so all arguments were being treated as true and random values that should not have passed the `if` criteria were being accepted and inserted. 
Tested downloading template files for the same protocol before and after the change several times and observed no more random values were being inserted in the time section.
=> Unexpected time values showing up in downloaded SEL template files

modules/CmpdRegBulkLoader/src/client/CmpdRegBulkLoader.coffee, modules/CmpdRegBulkLoader/src/client/CmpdRegBulkLoader.css, modules/CmpdRegBulkLoader/src/client/CmpdRegBulkLoader.html, modules/ServerAPI/src/client/Protocol.css
- Changed CmpdReg BulkLoader PicklistController to PicklistSelect2Controllers
- Updating the styling of errors, widths...etc. in the CSS
ACAS-646
- Validated and Registered compounds
- Used the type ahead to narrow list and make selections (see screenshot below)
- Verified each of the pick lists rendered the correct Red colors (see screenshot below) when in error states
=> ACAS-646: Update CmpdReg bulkloader picklists to be type ahead (PicklistSelect2Controller) picklists.

modules/GenericDataParser/src/client/GenericDataParser.coffee
- Removed the logic in GenericDataParser around multiple file uploads.  The logic was wrong as it was counting report files and image files when preventing duplicate experiment files. It would then prevent the user from moving forward if they provided a report file or image file with their upload.
- The reason I just removed the multiple experiment file logic is because the file widget already reports that the second file that was dragged and dropped is invalid, so the behavior that the UI stops the user from clicking next until they remove the invalid file seemed unnecessary. As long as the user knows that one file is valid and the second file uploaded is not valid, then the UI should allow the user to continue.
ACAS-650
- Validated report file and image file attachments work when …
=> ACAS-650: Fix report/image file uploading

modules/ServerAPI/src/client/Protocol.coffee
When making a new protocol with the Protocol Editor, users were unable to add new endpoints and save the protocol. When users clicked on the "Add Endpoint" button, nothing would happen. This was due to an issue where the @endpointControllers object that is part of adding, removing, and editing endpoint rows was not being initialized for new protocols. To fix, added logic specific for new protocols to initialize this. 
After making the change, successfully created and saved new protocols with endpoints using the endpoint editor.
=> Endpoint manager breaks creating new protocols

modules/ServerAPI/src/client/Protocol.coffee, modules/ServerAPI/src/server/routes/ProtocolServiceRoutes.coffee
When users would try to download template files when a protocol had no experiments associated with it, the download would fail. This is because to generate the template file, the backend logic finds all the endpoints associated with each experiment and compiles them to create the file. It doesn't look at the protocol's saved endpoints, and couldn't handle if there were no endpoints at all.
To fix, implemented new logic:
- Check if the protocol has experiments, if it does - extract the endpoints from the experiments and display them in the file
-  If the protocol doesn't have experiments, use the endpoints defined in the protocol
- If the protocol doesn't have any endpoints, don't add the section to the .csv when creating it
Created three protocols: one with experiments uploaded associated …
=> Download template does not fill endpoints when there are no experiments exist on the protocol

modules/ServerAPI/src/server/routes/CreateLiveDesignLiveReportForACAS.coffee
- One-liner fix for "username" attribute not being passed to function
Without this fix, the stacktrace is:
```
[ACAS] 2023-06-22T20:39:55.026Z error: 'Caught exception: TypeError: callback is not a function\n' +
--
'    at ChildProcess.<anonymous> (/home/runner/build/routes/CreateLiveDesignLiveReportForACAS.js:109:16)\n' +
'    at ChildProcess.emit (events.js:400:28)\n' +
'    at maybeClose (internal/child_process.js:1088:16)\n' +
'    at Socket.<anonymous> (internal/child_process.js:446:11)\n' +
'    at Socket.emit (events.js:400:28)\n' +
'    at Pipe.<anonymous> (net.js:686:12)'
```
N/A
I have not tested this, but I have tested that the adjacent route `redirectToNewLiveDesignLiveReportForExperiment` works fine, and this is really the only difference.
=> ACAS-687: Fix getUrlForNewLiveDesignReportForExperiment API

docker-compose.yml
See https://github.com/mcneilco/acas-roo-server/pull/445 & https://github.com/mcneilco/acas-postgres/pull/5.
Update db image tag to use the one with "pg_trgm" installed.
[ACAS-674](https://jira.schrodinger.com/browse/ACAS-674)
Verified the new image works with the changes in https://github.com/mcneilco/acas-roo-server/pull/445 without having to manually install pg_trgm extension.
=> ACAS-674: Bump db version to use the one with pg_trgm extension.

modules/ServerAPI/src/server/routes/ExperimentServiceRoutes.coffee
- ACAS node changes for restricting `/api/experiments/protocolCodename/:code`
- Pass allowed projects to the backend for filtering
**To reproduce**
Create an experiment in a restricted project and login as a user who does not have access to that project.
Go to the protocol browser window and search for the protocol 
Scroll down to the section titled: "Experiments using"
**Expectation**
Experiment in restricted project that the user does not have access to is not displayed
**Actual outcome**
Experiment in restricted project that the user does not have access to is displayed.
**Technical details**
This feature relies on the ACAS route here https://github.com/mcneilco/acas/blob/b8719989a424da9ccbc571a84c118d213774eaf3/modules/ServerAPI/src/server/routes/ExperimentServiceRoutes.coffee#L32: …
=> ACAS-699: Pass list of projects to backend to filter projects by acls

modules/CmpdReg/src/server/routes/CmpdRegRoutes.coffee, modules/CmpdRegAdmin/src/server/routes/CmpdRegAdminRoutes.coffee
- As part of ACAS-307 (https://github.com/mcneilco/acas/pull/1079) we started including analysis group values when fetching lot dependencies which can be very slow if there are a lot of experimental results.
- The lot details page check lot dependencies when loading the page and therefore the loading of some lot details pages slowed significantly with ACAS-307.
- This change adds a "include_analysis_group_values" parameter to the python ACAS client `get_lot_dependencies` method and defaults it true for backwards compatibility.
- This default for the actual acas route is false so the lot details page and any other page which loads dependencies of the lots sees a significant increase in speed.
ACAS-702
Ran acas client tests
Manually loaded a large 50K line experiment all to the same lot. …
=> ACAS-702: Include analysis group values parameter for faster depedency checks

modules/CmpdReg/src/server/routes/CmpdRegRoutes.coffee
- ACAS should return 404, not 500 when a lot does not exist.  Currently it returns 500 and on certain nginx proxied servers, the 500 error is swallowed and the front end cannot check for the error as it's replaced with an html structure.  Then end result is that the UI hangs when a lot does not exist instead of showing "Lot does not exist" on the page.
ACAS-702
Ran manual test in the UI to verify that the correct message is displayed.
Ran ACAS client tests and verified tests pass.
=> ACAS-701: Return status code 404 for get metalot route

modules/CmpdReg/src/client/custom/LotView_Custom.inc, modules/CmpdReg/src/client/custom/Lot_Custom.js
- Allows editing of notebook, synthesis date and notebook page fields by users who are able to edit lots.  This is something that is already by the API but restricted via the GUI.
ACAS-700
Created a lot via the GUI and verified these fields are all still required by the GUI when creating new.
Edited the lot and verified:
- The fields are required still when editing lot
- I could edit the lot chemist, synthesis and notebook pages now via the GUI
- I could not edit these fields as a user a cmpdreg user which did not have access to edit the lot.
=> ACAS-700: Make chemist, notebook page and synthesis date editable in the UI by authorized users after lot save.

.github/workflows/trigger-tag.yml
Updated the grep used to identify latest dev tag to be more selective and only look for ####.#.#-dev## formatted tags.
Ran grep locally and on linux machine to confirm it gives the right result. Have not tested in GitHub actions as it requires this being merged.
=> ACAS-716: Change tag grep to look for release tag format

modules/ServerAPI/src/client/SaltBrowser.coffee
The following was sourced from this GitHub issue filed by John McNeil: https://github.com/mcneilco/acas/issues/1117
**Expected Behavior**
When you open the CmpdReg Salts browser, click Create New Salt and enter a duplicate salt, you should receive an error that the salt exists
**Previous Behavior**
Follow the above steps, then the form clears and shows this
An error occured creating Salt . Please contact support for additional help.
The console shows:
Uncaught TypeError: this.$(...) is not a function
at Object.error (SaltBrowser.js:453:62)
at k (jquery.min.js:2:16920)
at Object.fireWith [as rejectWith] (jquery.min.js:2:17707)
at y (jquery.min.js:2:80829)
at XMLHttpRequest.d (jquery.min.js:2:86374)
**Fix This PR Addresses**
=> Update SaltBrowser.coffee to Provide Better Error Display to User

modules/CmpdReg/src/server/routes/CmpdRegRoutes.coffee
- Partially reverting #1047 until we get acls right to edit parent structures
- No changes to acasclient were required because we commented out a number of the tests previously due to flakiness
ACAS-723
- Ran acasclient tests for edit parent
- Verified I could login as a Creg user (non admin) and edit a parent if I could edit the lot.
=> ACAS-723: Revert edit parents acls

.github/workflows/docker-image.yml
ACAS builds take a while. It'd be nice to speed these up by caching docker layers.
I also threw in a change to the triggers of the CI workflow, as it seemed to be overeager and was triggering whenever a new branch was created and pushed, rather than only when tags (refs/tags) were pushed.
It will be tested by the GHA runs on this PR
=> Enable Docker build caching for ACAS

conf/config.properties.example, modules/GenericDataParser/src/server/generic_data_parser.R
- Changes the default short descriptions of protocol/experiments to null
- Makes configurable the default short descriptions of protocols/experiments
- This does not automatically set all protocols and experiments previously created to the default settings. This can be accomplished by running the following sqls:
```
update protocol set short_description = null where short_description like '%created by generic data parser';
update experiment set short_description = null where short_description like '%created by generic data parser';
```
ACAS-725
- Verified in the GUI that the protocol and experiments both had empty descriptions by default
- Verified in the database that the protocol and experiments both had empty descriptions by default
```
acas=> select short_description from protocol …
```
=> ACAS-725: Configurable sel created protocol/experiment text default to null

conf/config.properties.example, modules/GenericDataParser/src/server/generic_data_parser.R, modules/ServerAPI/src/server/CustomerSpecificServerFunctions.coffee, modules/ServerAPI/src/server/python/acas_ldclient/acasldclient.py
- Support for hyper restricted project "types" returned by some project services
- Adds config for requiring that project services return project.type when when uploading experiments
ACAS-712
Ran new acasclient tests with base ACAS system.
To HRP project types, modified the default CustomerSpecificServerFunctions.coffee to include a "type" field.
I also modified the acasclient test messages to match those produced when project types are enabled
Finally, I verified that the final test in acasclient `(Allowed) Unrestricted experiment proj1 with lot restricted proj2` becomes a fail because the lot project is hyper restricted.
=> ACAS-712: HRP project type support

modules/Components/src/client/BasicFileValidateAndSave.coffee
- Fixes issue where file is not deleted on "Load Another" by programmatically clicking the delete button.
- This was kind of a deep issue and there was a previous "hack" found on other modules that did this exact same thing so I went with this solution.
ACAS-318
=> ACAS-318: Delete file on Load another

modules/Components/src/client/ACASFormFields.coffee, modules/ServerAPI/src/client/AttachFile.coffee
I dug into this a little more and found that there are some subtle differences between `encodeURI` which is meant to encode an entire URL / URI and `encodeURIComponent` which is meant to encode a query string or path component in a URL. For more info: https://stackoverflow.com/questions/75980/when-are-you-supposed-to-use-escape-instead-of-encodeuri-encodeuricomponent
I found that a simple switch to encoding only the `fileValue` with `encodeURIComponent` fixes the issue with `#` characters.
https://schrodinger.atlassian.net/browse/ACAS-761
- Tested uploading an experiment file whose filename contained `#` and confirmed I could download it again
- Also tested a horrible file with name: `Generic Special Chars ! @ # $ % ^ & * ( ) - _ = + [ ] { } | \ / < > ' " ? ,.xlsx`. This filename gets …
=> ACAS-761: Fix download urls for experiment files containing # special character

modules/CodeTablesAdmin/src/server/routes/CodeTablesAdminRoutes.coffee, modules/Components/src/client/ACASFormFields.coffee, modules/Components/src/client/PickList.coffee, modules/Components/src/server/routes/CodeTableServiceRoutes.coffee, modules/ServerAPI/src/server/CustomerSpecificServerFunctions.coffee, modules/ServerAPI/src/server/routes/InventoryServiceRoutes.coffee
- See related acas-roo-server changes https://github.com/mcneilco/acas/pull/1148
- Updated code table acas form widget to type ahead search rather than pre-fetch all picklist items.
- In the case that there is a selected value, it will fetch the selected value only so that the intial value will be set. 
ACAS-710
- Ran acasclient tests to verify compatability.
- Uploaded thousands of data column/ column tree ls_type / ls_kind values to ddict value and verified the code table fields behaved properly in Experiment editor and protocol editor as well as those in each of the endpoint manage fields.
Demo video
=> ACAS-710: Code value picklists type ahead search

Dockerfile
The issue with our builds (ACAS-762) appears to be caused by this npm issue https://github.com/npm/cli/issues/7072 . That issue has been fixed in a new release of npm, but Node hasn't yet made a release. To get our builds unstuck I'd like to pin npm.
[ACAS-762](https://schrodinger.atlassian.net/browse/ACAS-762)
```
=> [linux/amd64 11/19] RUN     npm install -g gulp@4.0.2 forever@3.0.4 coffeescript@2.5.1                       329.3s
=> => # npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokid
=> => # ar 3 with 15x fewer dependencies                                                                              
=> => # npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated     
=> => …
```
=> ACAS-762 pin npm to get fix for too many connections issue 

modules/CmpdReg/src/server/routes/CmpdRegRoutes.coffee
- Delete exported search results that are > 24 hours since last modified after the export searchResults route is called
ACAS-764
1. Basic
Exported some search results and then ran: `touch -d "25 hours ago" privateUploads/exportedSearchResults/*.sdf`
Verified the files were cleaned up
2. Folder
Added a folder to exportedSearchResults and verified this did not produce and error and was skipped
3. Added a purposeful error inside the `cleanUpExportedSearchResults` function and verified that the exportSearchResults function continue to work (just to make sure this doesn't break export if it happens to error for some reason.
4. Deployed this to a stage server with a lot of old exported search results and verified it cleaned up old files when I exported search results.
=> ACAS-764: Clean up cmpdreg exported search results > 24 hours old

modules/Components/src/client/PickList.coffee
- Fix for Bulkloader picklists not loading introduced by [ACAS-710](https://github.com/mcneilco/acas/pull/1148)
- Bulkhead picklist collection does not provide a url so URLs are being formed like this:
- `/undefined?labelTextSearchTerm=Lo&maxHits=100&term=Lo&q=Lo` and getting 404s
- The fix is to only use the url if it is set on the collection model.
ACAS-769
Using breakpoints verified that Protocol Endpoint manager picklists use the Ajax call and function properly.
Using breakpoints verified that CmpdReg bulkloader whose collection is preemptively fetched and does not have a URL, does not try to issue additional Ajax calls and the select2 widget is populated and. works correctly.
=> ACAS-769: Fix Bulkloader picklists by only using new type ahead when a url is provided to selection

modules/GenericDataParser/src/server/generic_data_parser.R
- Produces warning if any values uploaded as a `Number` contain [0-9] but will be saved as Text.
ACAS-760
Added acasclient test https://github.com/mcneilco/acasclient/pull/162
=> ACAS-760: Warn users if Number values which contain numerics will be saved as Text

Dockerfile
- Bumped nodejs from 18.x to 20.x
- See equivalent changes for races and acas-roo-server
- https://github.com/mcneilco/racas/pull/92
- https://github.com/mcneilco/acas-roo-server/pull/463
ACAS-727
Ran acasclient tests after building all 3 branches of ACAS-727 locally
Poked around the UI and loaded all module menus, verified drop downs worked.
=> ACAS-727: Update to nodejs 20 LTS

conf/config.properties.example, modules/ServerAPI/src/server/routes/AuthorRoutes.coffee
- Add new configuration `server.projects.additionalProjectGrants` which confers access to an additional list of projects if the user has access to the project in the key of the configuration.
Example:
```
server.projects.additionalProjectGrants = {"PROJ-00000001": ["PROJ-00000002", "PROJ-00000003"]}
```
This would grant access to PROJ-00000002 and PROJ-00000003 to users with access to PROJ-00000001
ACAS-770
Test1) Basic test
- Patched the code change onto a server and granted myself only access to PROJ-00000001 through a CustomerSpecificServerFunction configuration.
- I set this config:
`server.projects.additionalProjectGrants =  {"PROJ-00000001": ["PROJ-00000002"]}`
Result:
I could access both "PROJ-00000001" and "PROJ-00000002" 
Test2) Same as test 1 but also verify this works when …
=> ACAS-770: Additional project grants configuration

modules/CodeTablesAdmin/src/server/routes/CodeTablesAdminRoutes.coffee
The search behind the Additional ACAS & Additional CReg scientists admin modules was broken by the changes in #148.
This fix reverts the changes, then updates the function call to `getCodeTableValuesInternal` to match the new expected function signature.
[ACAS-768](https://schrodinger.atlassian.net/browse/ACAS-768)
- Tested these modules in local dev environment and confirmed search behavior before & after fix
=> ACAS-768: Fix additional ACAS & CReg scientist module search

bin/setenv.sh, modules/GenericDataParser/src/server/generic_data_parser.R
- See related base R image changes here: https://github.com/mcneilco/racas/pull/93
- This pull request includes changes to support R-4.4.0. The changes involve updating the LD_LIBRARY_PATH and PATH environment variables based on the architecture of the system. Additionally, there are updates to the getExperimentByNameCheck and runMain functions to handle NA values correctly following:
https://cran.r-project.org/bin/windows/base/old/4.2.0/NEWS.R-4.2.0.html
> Calling && or || with either argument of length greater than one now gives a warning (which it is intended will become an error).
In 4.3.0 this became an error: https://cran.r-project.org/bin/windows/base/old/4.3.0/NEWS.R-4.3.0.html
> Calling && or || with LHS or (if evaluated) RHS of length greater than one is now always an error, …
=> ACAS-774: Support R-4.4.0 changes

.github/workflows/docker-image.yml, .github/workflows/tagger.yml, .github/workflows/trigger-tag.yml, .github/workflows/upmerge.yml
- Fixes deprecation warning by bumping GitHub actions dependencies which use node 20 https://github.com/actions/github-script?tab=readme-ov-file#v7
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, docker/metadata-action@v4, docker/setup-qemu-action@v2, docker/setup-buildx-action@v2, docker/login-action@v2, actions/setup-python@v4. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```
ACAS-536
- `Create Upmerge pull requests` https://github.com/mcneilco/acas/actions/runs/9421080099
- `Docker Image CI` triggered by this PR  - Gets past important GitHub action steps but failing because its testing 2024-1 but falling back to 2024-3 images …
=> ACAS-536: Upgrade Github Actions dependencies to fix node16 deprecation warnings

Dockerfile
Backporting patch from #1166 to earlier release branch
=> ACAS-744: Switch to vault.centos.org as a workaround for stream8 EOL

modules/ServerAPI/src/server/python/createLiveDesignLiveReportForACAS/create_lr_for_acas.py
Removed the prefix 'inlineFileValue_' from assays_to_add -> resultType
[ACAS-739](https://schrodinger.atlassian.net/browse/ACAS-739)
I tested this on new mapping and no error were logged.
I updated the mapping view query to previous mapping and no error were logged when I added the data to LR
=> ACAS-739: Open in LiveDesign fails for image uploads experiments

modules/GenericDataParser/src/server/generic_data_parser.R
- Returns a list of non-matching endpoints when comparing protocol and experiment endpoints and then adds new endpoints to the protocol by adding additional `metadata_column order` states.
ACAS-736
- Manually uploaded an experiment
- Changed an endpoint name and re-uploaded the experiment and verified the endpoint was added to the protocol and upon subsequent uploads did not receive a warning about the endpoint.
=> ACAS-736: Append new experiment endpoints to protocol endpoints

modules/ServerAPI/src/client/Protocol.coffee
- Fixes bug where clicking on rows in `Experiment Browser` an then rows in `Protocol Browser` with endpoint manager turned on would produce and alert `Cannot reinitialise DataTable.`
ACAS-734
- Reliably reproduced the problem by:
- Searching for an experiment in Experiment Browser and clicking a row
- Searching for a protocol in Protocol Browser and clicking a row
- Verified the alert went away using the same test
- Verified manually that both `Protocol Browser` and `Experiment Browser` functioned normally after the change.
=> ACAS-734: Scope experiment table controller to this

.github/workflows/upmerge.yml
- Fixes issue when commits is not a valid GitHub author e.g." `7f0ac61071e83580b32ae313004a0113b7a7df82 Tanay Makharia makharia@MacBook-Pro-83.local`
- The script will now fallback to set of default reviewers.
- Also removes reviewers that are the author of the PR to fix an unrelated issue when running the Script on this PR branch.
ACAS-780
Ran upmerge and verified the fix.
=> ACAS-780: Fallback reviewers

modules/ServerAPI/src/server/Bootstrap.coffee
- `pip3.6` was replaced with `pip` which uses the installed python 3.11 pip
- Fixes this error which was introduced in https://github.com/mcneilco/acas/pull/1164 
```
[acas] [ACAS] 2024-06-24T19:35:05.663Z info: 'Bootstrap being called'
[acas] [ACAS] 2024-06-24T19:35:05.664Z info: 'About to call python using command: pip3.6 install --upgrade --force-reinstall --user http://livedesign-internal-bbolt-darwin/livedesign/ldclient.tar.gz'
[acas] [ACAS] 2024-06-24T19:35:05.674Z info: ''
[acas] [ACAS] 2024-06-24T19:35:05.674Z warn: 'Error installing ld client. This can happen if Live Design was down during ACAS start or otherwise ACAS could not communicate with Live Design.  This is just a warning as LD client might already be installed and be the correction version.'
[acas] [ACAS] …
```
=> ACAS-782: Use pip rather than pip3.6

modules/ServerAPI/src/server/python/createLiveDesignLiveReportForACAS/create_lr_for_acas.py
- Fixes this error when opening an experiment in LiveDesign:
```
[acas] [ACAS] 2024-06-24T21:05:46.778Z error: 'Caught exception: RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: NaN\n' +
[acas]   '    at ServerResponse.writeHead (node:_http_server:352:11)\n' +
[acas]   '    at ServerResponse.writeHead (/home/runner/build/node_modules/on-headers/index.js:44:26)\n' +
[acas]   '    at ServerResponse.writeHead (/home/runner/build/node_modules/on-headers/index.js:44:26)\n' +
[acas]   '    at ServerResponse._implicitHeader (node:_http_server:338:8)\n' +
[acas]   '    at write_ (node:_http_outgoing:945:9)\n' +
[acas]   '    at ServerResponse.end (node:_http_outgoing:1056:5)\n' +
[acas]   '    at writeend (/home/runner/build/node_modules/express-session/index.js:270:22)\n' + …
```
=> ACAS-783: Fix package import error and message printing

Dockerfile, requirements.txt
- Adds ldclient python requirements to ACAS base image
ACAS-802
Verified image builds and that I could install ldclient without installing dependencies:
```
Defaulting to user installation because normal site-packages is not writeable
Collecting https://redacted.com/livedesign/ldclient.tar.gz
Downloading https://redcated.com/livedesign/ldclient.tar.gz (133 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.9/133.9 kB 718.2 kB/s eta 0:00:00
Preparing metadata (setup.py) ... done
Requirement already satisfied: requests<3.0.0,>=2.0.0 in /usr/local/lib/python3.11/site-packages (from ldclient==2024.4.2.dev0) (2.32.3)
Requirement already satisfied: Deprecated==1.2.10 in /usr/local/lib/python3.11/site-packages (from ldclient==2024.4.2.dev0) (1.2.10)
Requirement already satisfied: wrapt<2,>=1.10 in …
```
=> ACAS-802: Air gapped ACAS cannot install LDClient dependencies

modules/ServerAPI/src/server/Bootstrap.coffee
- Without internet, pip can't reach out to check dependencies so it fails.  We are now installing ldclient dependencies into the image before this step so there is no reason to check for dependencies.
- Also skip checking for pip upgrades which slow down startup when there is no internet with `WARNING: There was an error checking the latest version of pip.` (we don't upgrade pip anyway so its a pointless check).
ACAS-802
Ran the following command on an kubernetes cluster without internet and verified ldclient installed and functioned properly:
```
kubectl exec -n livedesign deployments/acas -c acas -it -- pip install --disable-pip-version-check --upgrade --force-reinstall --no-deps --user http://livedesign-internal/livedesign/ldclient.tar.gz
```
=> ACAS-802: Add --no-deps --disable-pip-version-check to bootstrap ldclient script

modules/CmpdReg/src/client/css/NewCmpdReg_nocompile.css, modules/Components/src/client/ACASFormChemicalStructureView.html
- The maestro sketcher min height increased from 500 to 520 pixels.  ACAS is styling is very right so I increased the size of all sketchers to the same height and a few surrounding items to match.
ACAS-815
Lots of clicking around on various components. 
Below are screenshots of those components before and after the change for Maestro Sketcher and OSS Ketcher sketcher.  I did not test the MarvinJS sketcher.
Search
Reg step 1
Reg step 2 (no sketcher but some of the same elements)
Edit parent step 1
Edit parent step 2  (no sketcher but some of the same elements)
New salt (cmpdreg)
New salt (acas salt module)
Search
Reg step 1
Reg step 2 (no sketcher but some of the same elements)
Edit parent step 1
Edit parent step 2  (no sketcher but some of the same elements)
New salt (cmpdreg)
New salt …
=> ACAS-815: Increase chemical sketcher height

app_template.coffee, conf/config.properties.example, package.json
- Switch from memory store to postgres database store for session
- Added a new config `config.all.server.sessionTimeOutMinutes` (default 1440 = 24 hours)
ACAS-823
- Ran ACAS client tests locally
- Basic test
- Logged into ACAS and verified login works.
- Restarted ACAS and verified I was still logged in when ACAS started.
- Tried logging after a few minutes and verified it was 
- Set the session time out 1 minute and restarted acas
- Logged back, waited one minute and verified I was logged out automatically
- 2 Replica test
- Setup acas with 2 replicas in kubernetes
- Logged into ACAS
- Deleted the pod I was logged into and continued to work on the same window I was using previously without having to log back in.
=> ACAS-828 Use postgres for session management

Dockerfile
- Removes pinned npm version now that 18.20.1 has been released https://nodejs.org/en/blog/release/v18.20.1
ACAS-762
TBD on merge since we don't do mule-arch builds on PRs
=> ACAS-762-revert

app_template.coffee, conf/config.properties.example, package.json
- Switch from memory store to postgres database store for session
- Added a new config `config.all.server.sessionTimeOutMinutes` (default 1440 = 24 hours)
ACAS-823
- Ran ACAS client tests locally
- Basic test
- Logged into ACAS and verified login works.
- Restarted ACAS and verified I was still logged in when ACAS started.
- Tried logging after a few minutes and verified it was 
- Set the session time out 1 minute and restarted acas
- Logged back, waited one minute and verified I was logged out automatically
- 2 Replica test
- Setup acas with 2 replicas in kubernetes
- Logged into ACAS
- Deleted the pod I was logged into and continued to work on the same window I was using previously without having to log back in.
=> Revert "Revert "ACAS-828 Use postgres for session management""

modules/CmpdRegBulkLoader/src/client/CmpdRegBulkLoader.html
The UI looks buggy when an SDF property with a long name is uploaded. This PR fixes the CSS to overflow even if it has to break a word.
Manually in local UI:
=> ACAS-669: Fix text overflow of long sdf property name

modules/ServerAPI/src/client/SaltBrowser.coffee, modules/ServerAPI/src/client/SaltBrowser.html
Reported issue was a typo in user instructions. I also noticed use of color on buttons was inconsistent with the rest of the app, and there was a layout issue with the confirmation buttons on the Edit salt confirmation dialog.
- Fixed `sepcify` -> `specify` typo
- Removed `btn-primary` and `btn-danger` classes from most buttons in the workflow so `btn-danger` is only used on Delete dialogs. Switched Save / Update dialogs to `btn-success` (green)
- Removed the Cancel button from dialogs that had Back / Cancel / Save. The Back button already works to go backward and the wizard is only 2 steps deep, so I found the Cancel button to be unnecessary
Manual testing. See video (sorry for low resolution):
https://github.com/user-attachments/assets/1f0f44e4-bb28-455e-ac9f-84d0bfbe4cf4
=> ACAS-814: Fix typo and styling on Salt browser/editor

modules/ServerAPI/src/client/SaltBrowser.coffee, modules/ServerAPI/src/client/SaltBrowser.html
This PR adds the "allow cmpd registration" check that already exists on CReg single and bulk pages into the Salt Browser, since it also relies on chemistry services. Create, Edit, and Download buttons are disabled if compound registration is currently unavailable due to a need for a restandardization or due to unavailable chemistry services.
Tested by switching local roo to bbchem mode and pointing at a remove bbchem instance, which triggered some errors / failures from the allowCmpdRegistration route.
The table is still visible but the buttons at the top are disabled
Viewing and deleting is still available but editing is blocked
=> ACAS-786: Add restandardization check to SaltBrowser

modules/CmpdRegBulkLoader/src/client/CmpdRegBulkLoader.coffee, modules/CmpdRegBulkLoader/src/client/CmpdRegBulkLoader.html, modules/Components/src/client/PickList.coffee
The original ticket was narrowly scoped to provide a date picker when entering the lot date synthesized. I did that, and then extended it to also provide dropdowns for any fields that have constrained possible values / data dictionaries.
https://schrodinger.atlassian.net/browse/ACAS-834
Tested locally:
- Changing dbProperty back and forth between normal, dropdown, and date type parameters
- Submitting the form for validation and inspecting the request to confirm all types get the defaultValue inserted
- Tested creating a template, and how the form renders when a premade template is selected and then the file is loaded.
Dropdown:
Date picker:
- Many of the cmpdreg routes don't support searching by labelText so they don't update when a user types into the select2 search box. @brianbolt do …
=> ACAS-834: Provide appropriate inputs for bulk loader default values

modules/CmpdRegBulkLoader/src/client/CmpdRegBulkLoader.css
#1204 changed styling to allow long property names to overlap, but this introduced a new styling issue:
This PR contains the CSS fix for that issue
Locally:
=> ACAS-669: Follow-up fix to CSS for SDF bulk loader when dealing with long property names

modules/CurveAnalysis/src/server/renderCurve.R
Description
If http request &mostRecentCurveColor is supplied as "none" or "false" then the global config option is disabled.
Sort descending by curve recordedDate is removed. However, if mostRecentCurveColor is enabled, then only that curve is moved to the top of the plot.
Because of these changes, if the request includes &plotColors aligned in order with &curveIds, that color assignment is respected
Related Issue
Tracked in a user issue tracking system
This change works with changes to racas rendering.R
How Has This Been Tested?
Stage and prod testing, then stage again when this further issue was found
=> Nim 1808 curve overlay coloring v2

modules/ServerAPI/src/server/python/acas_ldclient/acasldclient.py
- Adds include_users=False to client.projects call to decrease the amount of data fetched/returned since we don't actually use the users returned in this call.
https://schrodinger.atlassian.net/browse/ACAS-854
Patched this into a server which was returning more data than the allowed buffer (1MB at that time) and causing json parsing issue when trying to parse a truncated stdout.
Verified that this decreased the amount of data returned by the call and the data returned was < 1MB and could be parsed correctly.
Verified that the Experiments Editor page loaded correctly after this change.
=> ACAS-854: Don't include users in project fetch

conf/config.properties.example
- These are the additional configuration to go with CmpdReg standardization as part of allowing multiple workers to work on standardization dry run. Related to https://github.com/mcneilco/acas-roo-server/pull/479 
ACAS-855
Verified I could toggle anyone of these settings, restart ACAS and they affected the behavior according to their purpose.
=> ACAS-855: Configs for allow multiple workers to work on dry run standardization
